execute @a[score_InGame_min=1,score_Class_min=6,score_Class=6,score_Spell3_min=1799,m=2,team=Blue] ~ ~ ~ /scoreboard players set @e[team=!Blue,r=10,tag=IsPlaying,score_EffDamage=1002] EffDamage 1002
execute @a[score_InGame_min=1,score_Class_min=6,score_Class=6,score_Spell3_min=1799,m=2,team=Blue] ~ ~ ~ /scoreboard players set @e[team=!Blue,r=10,tag=IsPlaying,score_EffSlow=3040] EffSlow 3040
execute @a[score_InGame_min=1,score_Class_min=6,score_Class=6,score_Spell3_min=1799,m=2,team=Blue] ~ ~ ~ /scoreboard players set @e[team=Blue,r=10,tag=IsPlaying,score_EffHeal=2002] EffHeal 2002
execute @a[score_InGame_min=1,score_Class_min=6,score_Class=6,score_Spell3_min=1799,m=2,team=Blue] ~ ~ ~ /effect @e[team=Orange,r=10,tag=IsPlaying] blindness 3 1 true
execute @a[score_InGame_min=1,score_Class_min=6,score_Class=6,score_Spell3_min=1799,m=2,team=Blue] ~ ~ ~ /scoreboard players set @e[team=!Blue,r=10,tag=IsPlaying] TouchBy 6
execute @a[score_Class_min=6,score_Class=6,score_Spell3_min=1799] ~ ~ ~ /playsound entity.firework.twinkle record @a[r=30] ~ ~ ~ 2 1 1
execute @a[score_InGame_min=1,score_Class_min=6,score_Class=6,score_Spell3_min=1799,m=2,team=Orange] ~ ~ ~ /scoreboard players set @e[team=!Orange,r=10,tag=IsPlaying,score_EffDamage=1002] EffDamage 1002
execute @a[score_InGame_min=1,score_Class_min=6,score_Class=6,score_Spell3_min=1799,m=2,team=Orange] ~ ~ ~ /scoreboard players set @e[team=!Orange,r=10,tag=IsPlaying,score_EffSlow=3040] EffSlow 3040
execute @a[score_InGame_min=1,score_Class_min=6,score_Class=6,score_Spell3_min=1799,m=2,team=Orange] ~ ~ ~ /scoreboard players set @e[team=Orange,r=10,tag=IsPlaying,score_EffHeal=2002] EffHeal 2002
execute @a[score_InGame_min=1,score_Class_min=6,score_Class=6,score_Spell3_min=1799,m=2,team=Orange] ~ ~ ~ /effect @e[team=Blue,r=10,tag=IsPlaying] blindness 3 1 true
execute @a[score_InGame_min=1,score_Class_min=6,score_Class=6,score_Spell3_min=1799,m=2,team=Orange] ~ ~ ~ /scoreboard players set @e[team=!Orange,r=10,tag=IsPlaying] TouchBy 6
execute @e[score_InGame_min=1,score_Class=6,score_Class_min=6,score_Spell2_min=399,score_Spell2=399,m=2,team=Blue] ~ ~ ~ /summon Silverfish ~ ~ ~ {Tags:["062B","Blue","NotOrange"]}
scoreboard players set @e[type=Silverfish,tag=062B] Class -6
execute @e[type=Silverfish,score_Class_min=-6,score_Class=-6] ~ ~ ~ /scoreboard players set @e[r=7,team=!Blue,tag=IsPlaying,score_EffSlow=1002] EffSlow 1002
execute @e[type=Silverfish,score_Class_min=-6,score_Class=-6] ~ ~ ~ /scoreboard players set @e[r=7,team=!Blue,tag=IsPlaying,score_EffPoison=1002] EffPoison 1002
execute @e[type=Silverfish,score_Class_min=-6,score_Class=-6] ~ ~ ~ /scoreboard players set @e[r=7,team=!Blue,tag=IsPlaying,score_EffNoMove=2] EffNoMove 2
execute @e[type=Silverfish,score_Class_min=-6,score_Class=-6] ~ ~ ~ /particle reddust ~ ~0.2 ~ 4 0 4 1 10 force
execute @e[type=Silverfish,score_Class_min=-6,score_Class=-6] ~ ~ ~ /scoreboard players set @e[r=7,team=!Blue,tag=IsPlaying] TouchBy 6
execute @e[type=Silverfish,score_Class_min=-6,score_Class=-6,score_Timer_min=-101,score_Timer=-101] ~ ~ ~ /summon armor_stand ~ ~-72 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Blue"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=Silverfish,score_Class_min=-6,score_Class=-6,score_Timer_min=-141,score_Timer=-141] ~ ~ ~ /summon armor_stand ~ ~-72 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Blue"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=Silverfish,score_Class_min=-6,score_Class=-6,score_Timer_min=-181,score_Timer=-181] ~ ~ ~ /summon armor_stand ~ ~-72 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Blue"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[score_InGame_min=1,score_Class=6,score_Class_min=6,score_Spell2_min=399,score_Spell2=399,m=2] ~ ~ ~ /playsound weather.rain record @a[r=10] ~ ~ ~ 2 2 1
execute @e[score_InGame_min=1,score_Class=6,score_Class_min=6,score_Spell2_min=398,score_Spell2=398,m=2] ~ ~ ~ /scoreboard players set @e[type=Silverfish,r=3,c=1] Timer -100
execute @e[score_InGame_min=1,score_Class=6,score_Class_min=6,score_Spell2_min=399,score_Spell2=399,m=2,team=Orange] ~ ~ ~ /summon Silverfish ~ ~ ~ {Tags:["062R","Orange","NotBlue"]}
scoreboard players set @e[type=Silverfish,tag=062R] Class 6
execute @e[type=Silverfish,score_Class_min=6,score_Class=6] ~ ~ ~ /scoreboard players set @e[r=7,team=!Orange,tag=IsPlaying,score_EffSlow=1002] EffSlow 1002
execute @e[type=Silverfish,score_Class_min=6,score_Class=6] ~ ~ ~ /scoreboard players set @e[r=7,team=!Orange,tag=IsPlaying,score_EffPoison=1002] EffPoison 1002
execute @e[type=Silverfish,score_Class_min=6,score_Class=6] ~ ~ ~ /scoreboard players set @e[r=7,team=!Orange,tag=IsPlaying,score_EffNoMove=2] EffNoMove 2
execute @e[type=Silverfish,score_Class_min=6,score_Class=6] ~ ~ ~ /particle reddust ~ ~0.2 ~ 4 0 4 1 10 force
execute @e[type=Silverfish,score_Class_min=6,score_Class=6] ~ ~ ~ /scoreboard players set @e[r=7,team=!Orange,tag=IsPlaying] TouchBy 6
execute @e[type=Silverfish,score_Class_min=6,score_Class=6,score_Timer_min=-101,score_Timer=-101] ~ ~ ~ /summon armor_stand ~ ~-72 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Orange"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=Silverfish,score_Class_min=6,score_Class=6,score_Timer_min=-141,score_Timer=-141] ~ ~ ~ /summon armor_stand ~ ~-72 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Orange"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=Silverfish,score_Class_min=6,score_Class=6,score_Timer_min=-181,score_Timer=-181] ~ ~ ~ /summon armor_stand ~ ~-72 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Orange"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}]}
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,team=Blue] ~ ~ ~ /summon Skeleton ~-1 ~-2 ~1 {CustomName:Archer,CustomNameVisible:false,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:skull",Damage:0,Count:1b}],HandItems:[{id:"minecraft:bow",Count:1b},{id:"minecraft:air",Count:1b}],LeftHanded:false,Tags:["SpawnAnime","NotOrange","Blue","062B","Life10"]}
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,team=Blue] ~ ~ ~ /summon Skeleton ~-1 ~-2 ~-1 {CustomName:Archer,CustomNameVisible:false,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:skull",Damage:0,Count:1b}],HandItems:[{id:"minecraft:bow",Count:1b},{id:"minecraft:air"}],LeftHanded:false,Tags:["SpawnAnime","NotOrange","Blue","062B","Life10"]}
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,team=Blue] ~ ~ ~ /summon Skeleton ~1 ~-2 ~ {CustomName:Archer,CustomNameVisible:false,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:skull",Damage:0,Count:1b}],HandItems:[{id:"minecraft:bow",Count:1b},{id:"minecraft:air"}],LeftHanded:false,Tags:["SpawnAnime","NotOrange","Blue","062B","Life10"]}
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299] ~ ~ ~ /playsound entity.zombie_pig.death record @a[r=5] ~ ~ ~ 2 2 1
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,team=Orange] ~ ~ ~ /summon Skeleton ~ ~-2 ~-1 {CustomName:Archer,CustomNameVisible:false,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:skull",Damage:0,Count:1b}],HandItems:[{id:"minecraft:bow",Count:1b},{id:"minecraft:air",Count:1b}],LeftHanded:false,Tags:["SpawnAnime","NotBlue","Orange","062R","Life10"]}
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,team=Orange] ~ ~ ~ /summon Skeleton ~-1 ~-2 ~1 {CustomName:Archer,CustomNameVisible:false,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:skull",Damage:0,Count:1b}],HandItems:[{id:"minecraft:bow",Count:1b},{id:"minecraft:air",Count:1b}],LeftHanded:false,Tags:["SpawnAnime","NotBlue","Orange","062R","Life10"]}
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,team=Orange] ~ ~ ~ /summon Skeleton ~1 ~-2 ~1 {CustomName:Archer,CustomNameVisible:false,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:skull",Damage:0,Count:1b}],HandItems:[{id:"minecraft:bow",Count:1b},{id:"minecraft:air",Count:1b}],LeftHanded:false,Tags:["SpawnAnime","NotBlue","Orange","062R","Life10"]}
execute @a[score_TouchBy_min=6,score_TouchBy=6,score_InGame_min=1,score_TakeDamage_min=2000,score_TakeDamage=2999,m=2,score_EffPoison_min=1] ~ ~ ~ /particle enchantmenttable ~ ~1 ~ 0.5 1 0.5 0 20 force
execute @a[score_TouchBy_min=6,score_TouchBy=6,score_InGame_min=1,score_TakeDamage_min=2000,score_TakeDamage=2999,m=2,score_EffPoison_min=1] ~ ~ ~ /particle reddust ~ ~1 ~ 0.5 1 0.5 0.005 20 force
scoreboard players set @a[score_Class_min=6,score_Class=6,score_UseFishing_min=2,score_UseFishing=2,score_InGame_min=1,m=2] Spell1 300
scoreboard players set @a[score_Class_min=6,score_Class=6,score_UsePotion_min=2,score_UsePotion=2,score_InGame_min=1,m=2] Spell2 400
scoreboard players set @a[score_Class_min=6,score_Class=6,score_UseXp_min=2,score_UseXp=2,score_InGame_min=1,m=2] Spell3 1800
replaceitem entity @a[score_Mana=89,score_Class_min=6,score_Class=6,score_InGame_min=1,score_Spell3=0,score_Spell3_min=0,m=2,score_EffSilence=0] slot.hotbar.3 dye 1 8 {display:{Name:"Not enough mana !"},ench:[{id:19,lvl:0}]}
scoreboard players remove @a[score_Class_min=6,score_Class=6,score_UseXp_min=2,score_UseXp=2] Mana 90
replaceitem entity @a[score_Mana=19,score_Class_min=6,score_Class=6,score_InGame_min=1,score_Spell2=0,score_Spell2_min=0,m=2,score_EffSilence=0] slot.hotbar.2 dye 1 8 {display:{Name:"Not enough mana !"},ench:[{id:19,lvl:0}]}
scoreboard players remove @a[score_Class_min=6,score_Class=6,score_UsePotion_min=2,score_UsePotion=2] Mana 20
replaceitem entity @a[score_Mana=29,score_Class_min=6,score_Class=6,score_InGame_min=1,score_Spell1=0,score_Spell1_min=0,m=2,score_EffSilence=0] slot.hotbar.1 dye 1 8 {display:{Name:"Not enough mana !"},ench:[{id:19,lvl:0}]}
scoreboard players remove @a[score_Class_min=6,score_Class=6,score_UseFishing_min=2,score_UseFishing=2] Mana 30
replaceitem entity @a[score_Mana_min=30,score_InGame_min=1,score_EffSilence=0,score_Spell1=0,score_Class_min=6,score_Class=6,m=2] slot.hotbar.1 minecraft:fishing_rod 1 0 {Unbreakable:1,ench:[{id:19,lvl:0}],display:{Name:"Archer Army  90✸  15s",Lore:["۞ 30 Mana","","+ Spawn 3 archer skeletons"]},HideFlags:63}
replaceitem entity @a[score_Mana_min=20,score_InGame_min=1,score_EffSilence=0,score_Spell2=0,score_Class_min=6,score_Class=6,m=2] slot.hotbar.2 minecraft:splash_potion 1 0 {Unbreakable:1,ench:[{id:19,lvl:0}],display:{Name:"Vital Energy Zone  20✸  20s",Lore:["۞ 20 Mana","","⚔ 2 Poison 1s ▢ Area Range 5","☀ 2 Slow 1s ▢ Area Range 5","+ 20% Protection 1s ▢ Area Range 5"]},HideFlags:63}
replaceitem entity @a[score_Mana_min=90,score_InGame_min=1,score_EffSilence=0,score_Spell3=0,score_Class_min=6,score_Class=6,m=2] slot.hotbar.3 minecraft:experience_bottle 1 0 {Unbreakable:1,ench:[{id:19,lvl:0}],display:{Name:"Fountain of Youth  30✸  90s",Lore:["۞ 90 Mana","","❤ 6 Heal ▢ Range 10","⚔ 6 Damage ▢ Range 10","☀ Stunt 2s ▢ Range 10","☀ Blindness 2s ▢ Range 10"]},HideFlags:63}
execute @a[score_EffNoDie=0,score_IsDead_min=2,score_IsDead=2,score_InGame_min=1,score_TouchBy_min=6,score_TouchBy=6,team=Orange] ~ ~ ~ /say met death under request of @p[score_Class_min=6,score_Class=6,team=Blue,score_InGame_min=1]
execute @a[score_EffNoDie=0,score_IsDead_min=2,score_IsDead=2,score_InGame_min=1,score_TouchBy_min=6,score_TouchBy=6,team=Blue] ~ ~ ~ /say met death under request of @p[score_Class_min=6,score_Class=6,team=Orange,score_InGame_min=1]
execute @a[score_EffNoDie=0,score_IsDead_min=2,score_IsDead=2,score_InGame_min=1,score_TouchBy_min=6,score_TouchBy=6,team=Orange] ~ ~ ~ /scoreboard players add @p[score_Class_min=6,score_Class=6,team=Blue,score_InGame_min=1,tag=!InTraining] KillNumber 1
execute @a[score_EffNoDie=0,score_IsDead_min=2,score_IsDead=2,score_InGame_min=1,score_TouchBy_min=6,score_TouchBy=6,team=Blue] ~ ~ ~ /scoreboard players add @p[score_Class_min=6,score_Class=6,team=Orange,score_InGame_min=1,tag=!InTraining] KillNumber 1