execute @a[score_Class=6,score_Class_min=6,score_Spell1=298,score_Spell1_min=298] ~ ~ ~ /particle largesmoke ~ ~1 ~ 1 1 1 0 20 force
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,score_Spell1=299,team=Blue] ~ ~ ~ /summon Skeleton ~2 ~-2 ~2 {CustomName:Archer,CustomNameVisible:false,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:skull",Damage:0,Count:1b}],HandItems:[{id:"minecraft:bow",Count:1b},{id:"minecraft:air",Count:1b}],LeftHanded:false,Tags:["SpawnAnime","NotOrange","Blue","062B","Life10"]}
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,score_Spell1=299,team=Blue] ~ ~ ~ /summon Skeleton ~-2 ~-2 ~-2 {CustomName:Archer,CustomNameVisible:false,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:skull",Damage:0,Count:1b}],HandItems:[{id:"minecraft:bow",Count:1b},{id:"minecraft:air"}],LeftHanded:false,Tags:["SpawnAnime","NotOrange","Blue","062B","Life10"]}
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,score_Spell1=299,team=Blue] ~ ~ ~ /summon Skeleton ~2 ~-2 ~-2 {CustomName:Archer,CustomNameVisible:false,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:skull",Damage:0,Count:1b}],HandItems:[{id:"minecraft:bow",Count:1b},{id:"minecraft:air"}],LeftHanded:false,Tags:["SpawnAnime","NotOrange","Blue","062B","Life10"]}
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,score_Spell1=299,team=Blue] ~ ~ ~ /summon Skeleton ~-2 ~-2 ~2 {CustomName:Archer,CustomNameVisible:false,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:884479}}},{id:"minecraft:skull",Damage:0,Count:1b}],HandItems:[{id:"minecraft:bow",Count:1b},{id:"minecraft:air"}],LeftHanded:false,Tags:["SpawnAnime","NotOrange","Blue","062B","Life10"]}
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,score_Spell1=299] ~ ~ ~ /playsound entity.zombie_pig.death record @a[r=5] ~ ~ ~ 2 2 1
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,score_Spell1=299,team=Orange] ~ ~ ~ /summon Skeleton ~2 ~-2 ~2 {IsBaby:1,CustomName:Archer,CustomNameVisible:false,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:skull",Damage:0,Count:1b}],HandItems:[{id:"minecraft:bow",Count:1b},{id:"minecraft:air",Count:1b}],LeftHanded:false,Tags:["SpawnAnime","NotBlue","Orange","062R","Life10"]}
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,score_Spell1=299,team=Orange] ~ ~ ~ /summon Skeleton ~-2 ~-2 ~-2 {IsBaby:1,CustomName:Archer,CustomNameVisible:false,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:skull",Damage:0,Count:1b}],HandItems:[{id:"minecraft:bow",Count:1b},{id:"minecraft:air",Count:1b}],LeftHanded:false,Tags:["SpawnAnime","NotBlue","Orange","062R","Life10"]}
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,score_Spell1=299,team=Orange] ~ ~ ~ /summon Skeleton ~2 ~-2 ~-2 {IsBaby:1,CustomName:Archer,CustomNameVisible:false,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:skull",Damage:0,Count:1b}],HandItems:[{id:"minecraft:bow",Count:1b},{id:"minecraft:air",Count:1b}],LeftHanded:false,Tags:["SpawnAnime","NotBlue","Orange","062R","Life10"]}
execute @a[score_Class=6,score_Class_min=6,score_Spell1_min=299,score_Spell1=299,team=Orange] ~ ~ ~ /summon Skeleton ~-2 ~-2 ~2 {IsBaby:1,CustomName:Archer,CustomNameVisible:false,ArmorItems:[{id:"minecraft:leather_boots",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_leggings",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:leather_chestplate",Count:1b,tag:{display:{color:16711680}}},{id:"minecraft:skull",Damage:0,Count:1b}],HandItems:[{id:"minecraft:bow",Count:1b},{id:"minecraft:air",Count:1b}],LeftHanded:false,Tags:["SpawnAnime","NotBlue","Orange","062R","Life10"]}
