execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,score_Spell3_min=1199,score_Spell3=1199,m=2] ~ ~ ~ /playsound entity.lightning.thunder record @a[r=15] ~ ~ ~ 2 0.5 1
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,score_Spell3_min=1199,score_Spell3=1199,m=2,team=Blue] ~ ~ ~ /summon silverfish ~ ~ ~ {Tags:["Blue"]}
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,score_Spell3_min=1199,score_Spell3=1199,m=2,team=Orange] ~ ~ ~ /summon silverfish ~ ~ ~ {Tags:["Orange"]}
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,score_Spell3_min=1198,score_Spell3=1198,m=2] ~ ~ ~ /scoreboard players set @e[type=silverfish,r=3,c=1] Timer -100
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,score_Spell3_min=1199,score_Spell3=1199,m=2,team=Blue] ~ ~ ~ /scoreboard players set @e[type=silverfish,r=3,c=1] Class -3
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,score_Spell3_min=1199,score_Spell3=1199,m=2,team=Orange] ~ ~ ~ /scoreboard players set @e[type=Silverfish,r=3,c=1] Class 3

execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[team=Orange,r=7,tag=IsPlaying,EffNoTp=2] EffNoTp 2
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /scoreboard players set @e[team=Blue,r=7,tag=IsPlaying,EffNoTp=2] EffNoTp 2
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /execute @e[team=Orange,score_Timer_min=8,score_Timer=8,tag=IsPlaying,r=7] ~ ~ ~ /scoreboard players set @e[team=Blue,r=5,tag=IsPlaying] EffInvulnerable 2
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ execute @e[team=Orange,score_Timer_min=28,score_Timer=28,tag=IsPlaying,r=7] ~ ~ ~ /scoreboard players set @e[team=Blue,r=3,tag=IsPlaying] EffInvulnerable 2
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ execute @e[team=Blue,score_Timer_min=28,score_Timer=28,tag=IsPlaying,r=7] ~ ~ ~ /scoreboard players set @e[team=Orange,r=5,tag=IsPlaying] EffInvulnerable 2
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ execute @e[team=Blue,score_Timer_min=8,score_Timer=8,tag=IsPlaying,r=7] ~ ~ ~ /scoreboard players set @e[team=Orange,r=3,tag=IsPlaying] EffInvulnerable 2
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /execute @e[team=Orange,r=7,tag=IsPlaying,score_Timer_min=30,score_Timer=30] ~ ~ ~ /summon Lightning_Bolt ~ ~ ~
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /execute @e[team=Orange,r=7,tag=IsPlaying,score_Timer_min=10,score_Timer=10] ~ ~ ~ /summon Lightning_Bolt ~ ~ ~
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /execute @e[team=Blue,r=7,tag=IsPlaying,score_Timer_min=10,score_Timer=10] ~ ~ ~ /summon Lightning_Bolt ~ ~ ~
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /execute @e[team=Blue,r=7,tag=IsPlaying,score_Timer_min=30,score_Timer=30] ~ ~ ~ /summon Lightning_Bolt ~ ~ ~
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[tag=IsPlaying,team=Orange,r=7,score_EffSlow=1002] EffSlow 1002
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /scoreboard players set @e[tag=IsPlaying,team=Blue,r=7,score_EffSlow=1002] EffSlow 1002
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[team=Orange,r=7,tag=IsPlaying] C3 400
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /scoreboard players set @e[team=Blue,r=7,tag=IsPlaying] C3 400
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[team=Orange,score_Timer_min=28,score_Timer=28,tag=IsPlaying,r=7] EffResistance 1002
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[team=Orange,score_Timer_min=8,score_Timer=8,tag=IsPlaying,r=7] EffResistance 1002
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /scoreboard players set @e[team=Blue,score_Timer_min=28,score_Timer=28,tag=IsPlaying,r=7] EffResistance 1002
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ scoreboard players set @e[team=Blue,score_Timer_min=8,score_Timer=8,tag=IsPlaying,r=7] EffResistance 1002
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[team=Orange,r=7,tag=IsPlaying,score_Timer_min=30,score_Timer=30] TouchBy 3
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[team=Orange,r=7,tag=IsPlaying,score_Timer_min=10,score_Timer=10] TouchBy 3
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /scoreboard players set @e[team=Blue,r=7,tag=IsPlaying,score_Timer_min=30,score_Timer=30] TouchBy 3
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /scoreboard players set @e[team=Blue,r=7,tag=IsPlaying,score_Timer_min=10,score_Timer=10] TouchBy 3
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3,score_Timer_min=-101,score_Timer=-101] ~ ~ ~ /summon armor_stand ~ ~200 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:["RotBase","Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Blue"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3,score_Timer_min=-141,score_Timer=-141] ~ ~ ~ /summon armor_stand ~ ~200 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:["RotBase","Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Blue"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3,score_Timer_min=-181,score_Timer=-181] ~ ~ ~ /summon armor_stand ~ ~200 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:["RotBase","Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Blue"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=silverfish,score_Class_min=3,score_Class=3,score_Timer_min=-101,score_Timer=-101] ~ ~ ~ /summon armor_stand ~ ~200 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:["RotBase","Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Orange"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=silverfish,score_Class_min=3,score_Class=3,score_Timer_min=-141,score_Timer=-141] ~ ~ ~ /summon armor_stand ~ ~200 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:["RotBase","Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Orange"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=silverfish,score_Class_min=3,score_Class=3,score_Timer_min=-181,score_Timer=-181] ~ ~ ~ /summon armor_stand ~ ~200 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:["RotBase","Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Orange"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}

execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /particle cloud ~ ~7 ~ 3 0.3 3 0 20 force
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /particle cloud ~ ~7 ~ 3 0.3 3 0 20 force
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /particle largeexplode ~ ~7 ~ 3 0.3 3 0 5 force
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /particle largeexplode ~ ~7 ~ 3 0.3 3 0 5 force