execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,score_Spell3_min=1198,score_Spell3=1198,m=2,team=Blue] ~ ~ ~ /scoreboard players set @e[type=silverfish,r=3,c=1] Class -3
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[team=Orange,r=7,tag=IsPlaying,EffNoTp=2] EffNoTp 2
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /execute @e[team=Orange,score_Timer_min=8,score_Timer=8,tag=IsPlaying,r=7] ~ ~ ~ /scoreboard players set @e[team=Blue,r=5,tag=IsPlaying] EffInvulnerable 2
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ execute @e[team=Orange,score_Timer_min=28,score_Timer=28,tag=IsPlaying,r=7] ~ ~ ~ /scoreboard players set @e[team=Blue,r=3,tag=IsPlaying] EffInvulnerable 2
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /execute @e[team=Orange,r=7,tag=IsPlaying,score_Timer_min=30,score_Timer=30] ~ ~ ~ /summon Lightning_Bolt ~ ~ ~
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /execute @e[team=Orange,r=7,tag=IsPlaying,score_Timer_min=10,score_Timer=10] ~ ~ ~ /summon Lightning_Bolt ~ ~ ~
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[tag=IsPlaying,team=Orange,r=7,score_EffSlow=1002] EffSlow 1002
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[team=Orange,r=7,tag=IsPlaying] C3 400
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[team=Orange,score_Timer_min=28,score_Timer=28,tag=IsPlaying,r=7] EffResistance 1002
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[team=Orange,score_Timer_min=8,score_Timer=8,tag=IsPlaying,r=7] EffResistance 1002
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[team=Orange,r=7,tag=IsPlaying,score_Timer_min=30,score_Timer=30] TouchBy 3
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[team=Orange,r=7,tag=IsPlaying,score_Timer_min=10,score_Timer=10] TouchBy 3
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3,score_Timer_min=-101,score_Timer=-101] ~ ~ ~ /summon armor_stand ~ ~-72 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Blue"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3,score_Timer_min=-141,score_Timer=-141] ~ ~ ~ /summon armor_stand ~ ~-72 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Blue"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=silverfish,score_Class_min=-3,score_Class=-3,score_Timer_min=-181,score_Timer=-181] ~ ~ ~ /summon armor_stand ~ ~-72 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Blue"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,score_Spell3_min=1199,score_Spell3=1199,m=2,team=Blue] ~ ~ ~ /summon silverfish ~ ~ ~ {Tags:["Blue"]}
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,score_Spell3_min=1198,score_Spell3=1198,m=2] ~ ~ ~ /scoreboard players set @e[type=silverfish,r=3,c=1] Timer -100
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,score_Spell3_min=1199,score_Spell3=1199,m=2] ~ ~ ~ /playsound entity.lightning.thunder record @a[r=15] ~ ~ ~ 2 0.5 1
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,score_Spell3_min=1199,score_Spell3=1199,m=2,team=Orange] ~ ~ ~ /summon silverfish ~ ~ ~ {Tags:["Orange"]}
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,score_Spell3_min=1198,score_Spell3=1198,m=2,team=Orange] ~ ~ ~ /scoreboard players set @e[type=Silverfish,r=3,c=1] Class 3
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /scoreboard players set @e[team=Blue,r=7,tag=IsPlaying,EffNoTp=2] EffNoTp 2
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ execute @e[team=Blue,score_Timer_min=8,score_Timer=8,tag=IsPlaying,r=7] ~ ~ ~ /scoreboard players set @e[team=Orange,r=3,tag=IsPlaying] EffInvulnerable 2
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ execute @e[team=Blue,score_Timer_min=28,score_Timer=28,tag=IsPlaying,r=7] ~ ~ ~ /scoreboard players set @e[team=Orange,r=5,tag=IsPlaying] EffInvulnerable 2
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /execute @e[team=Blue,r=7,tag=IsPlaying,score_Timer_min=30,score_Timer=30] ~ ~ ~ /summon Lightning_Bolt ~ ~ ~
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /execute @e[team=Blue,r=7,tag=IsPlaying,score_Timer_min=10,score_Timer=10] ~ ~ ~ /summon Lightning_Bolt ~ ~ ~
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /scoreboard players set @e[tag=IsPlaying,team=Blue,r=7,score_EffSlow=1002] EffSlow 1002
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /scoreboard players set @e[team=Blue,r=7,tag=IsPlaying] C3 400
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ scoreboard players set @e[team=Blue,score_Timer_min=8,score_Timer=8,tag=IsPlaying,r=7] EffResistance 1002
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /scoreboard players set @e[team=Blue,score_Timer_min=28,score_Timer=28,tag=IsPlaying,r=7] EffResistance 1002
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /scoreboard players set @e[team=Blue,r=7,tag=IsPlaying,score_Timer_min=30,score_Timer=30] TouchBy 3
execute @e[type=silverfish,score_Class_min=3,score_Class=3] ~ ~ ~ /scoreboard players set @e[team=Blue,r=7,tag=IsPlaying,score_Timer_min=10,score_Timer=10] TouchBy 3
execute @e[type=silverfish,score_Class_min=3,score_Class=3,score_Timer_min=-101,score_Timer=-101] ~ ~ ~ /summon armor_stand ~ ~-72 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Orange"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=silverfish,score_Class_min=3,score_Class=3,score_Timer_min=-141,score_Timer=-141] ~ ~ ~ /summon armor_stand ~ ~-72 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Orange"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=silverfish,score_Class_min=3,score_Class=3,score_Timer_min=-181,score_Timer=-181] ~ ~ ~ /summon armor_stand ~ ~-72 ~ {Tags:["Base"],NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Orange"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,m=2,score_UseCarrot_min=2,score_UseCarrot=2,team=Blue] ~ ~ ~ /execute @e[team=Orange,score_C3_min=1] ~ ~ ~ /scoreboard players set @e[team=Blue,r=4,score_InGame_min=1,score_EffInvulnerable=2] EffInvulnerable 2
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,m=2,score_UseCarrot=2,score_UseCarrot_min=2,team=Blue] ~ ~ ~ /execute @e[team=Orange,score_C3_min=1] ~ ~ ~ /summon Lightning_Bolt ~ ~ ~
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,m=2,score_UseCarrot=2,score_UseCarrot_min=2,team=Blue] ~ ~ ~ /scoreboard players set @e[team=Orange,score_C3_min=1,score_C3=390] C3 0
scoreboard players set @e[type=armor_stand,score_Class_min=-3,score_Class=-3] DirSpeed 100
scoreboard players set @e[type=armor_stand,score_Class_min=-3,score_Class=-3] DirCollision 1
execute @e[type=armor_stand,score_Class_min=-3,score_Class=-3] ~ ~ ~ /scoreboard players set @e[team=!Blue,tag=IsPlaying,r=3] C3 200
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,m=2,score_UseCarrot=2,score_UseCarrot_min=2,team=Blue] ~ ~ ~ /scoreboard players set @e[team=Orange,score_C3_min=1] TouchBy 3
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,m=2,score_UseCarrot=2,score_UseCarrot_min=2] ~ ~ ~ /summon Lightning_Bolt ~ ~7 ~
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,m=2,score_UseCarrot_min=2,score_UseCarrot=2,team=Orange] ~ ~ ~ /execute @e[team=Orange,score_C3_min=1] ~ ~ ~ /scoreboard players set @e[team=Orange,r=4,score_InGame_min=1,score_EffInvulnerable=2] EffInvulnerable 2
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,m=2,score_UseCarrot=2,score_UseCarrot_min=2,team=Orange] ~ ~ ~ /execute @e[team=Blue,score_C3_min=1] ~ ~ ~ /summon Lightning_Bolt ~ ~ ~
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,m=2,score_UseCarrot=2,score_UseCarrot_min=2,team=Orange] ~ ~ ~ /scoreboard players set @e[team=Blue,score_C3_min=1,score_C3=390] C3 0
scoreboard players set @e[type=armor_stand,score_Class_min=3,score_Class=3] DirSpeed 100
scoreboard players set @e[type=armor_stand,score_Class_min=3,score_Class=3] DirCollision 1
execute @e[type=armor_stand,score_Class_min=3,score_Class=3] ~ ~ ~ /scoreboard players set @e[team=!Orange,tag=IsPlaying,r=3] C3 200
execute @a[score_InGame_min=1,score_Class_min=3,score_Class=3,m=2,score_UseCarrot=2,score_UseCarrot_min=2,team=Orange] ~ ~ ~ /scoreboard players set @e[team=Blue,score_C3_min=1] TouchBy 3
execute @a[score_Class_min=3,score_Class=3,score_InGame_min=1,m=2,score_Spell1_min=120,team=Blue] ~ ~ ~ /scoreboard players set @e[team=Orange,tag=IsPlaying,r=2] C3 400
execute @a[score_Class_min=3,score_Class=3,score_InGame_min=1,m=2,score_Spell1_min=120,team=Blue] ~ ~ ~ /scoreboard players set @e[team=Orange,tag=IsPlaying,r=2,score_EffSlow=3020] EffSlow 3020
execute @a[score_Class_min=3,score_Class=3,score_InGame_min=1,m=2,score_Spell1_min=139] ~ ~ ~ /playsound entity.enderdragon.flap record @a[r=30] ~ ~ ~ 2 2 1
scoreboard players set @e[score_Class_min=3,score_Class=3,score_InGame_min=1,m=2,score_Spell1_min=139] EffSpeed 3002
execute @a[score_Class_min=3,score_Class=3,score_InGame_min=1,m=2,score_Spell1_min=120,team=Orange] ~ ~ ~ /scoreboard players set @e[team=Blue,tag=IsPlaying,r=2] C3 400
execute @a[score_Class_min=3,score_Class=3,score_InGame_min=1,m=2,score_Spell1_min=120,team=Orange] ~ ~ ~ /scoreboard players set @e[team=Blue,tag=IsPlaying,r=2,score_EffSlow=3020] EffSlow 3020
replaceitem entity @a[score_InGame_min=1,score_Class_min=3,score_Class=3,score_EffNoMove_min=1,score_Spell1=0,m=2] slot.hotbar.1 minecraft:barrier 1 0 {display:{Name:"Don't Move !"}}
execute @a[score_TouchBy_min=3,score_TouchBy=3,score_InGame_min=1,score_TakeDamage_min=2000,score_TakeDamage=2999,m=2,score_EffPoison_min=1] ~ ~ ~ /particle spell ~ ~1 ~ 0.3 1 0.3 0 10 force
execute @a[score_TouchBy_min=3,score_TouchBy=3,score_InGame_min=1,score_TakeDamage_min=2000,score_TakeDamage=2999,m=2,score_EffPoison_min=1] ~ ~ ~ /particle sweepAttack ~ ~1 ~ 0.5 1 0.5 0 3 force
scoreboard players set @a[score_Class_min=3,score_Class=3,score_UseFishing_min=2,score_UseFishing=2,score_InGame_min=1,m=2] Spell1 140
scoreboard players set @a[score_Class_min=3,score_Class=3,score_UseCarrot_min=2,score_UseCarrot=2,score_InGame_min=1,m=2] Spell2 100
scoreboard players set @a[score_Class_min=3,score_Class=3,score_UsePotion_min=2,score_UsePotion=2,score_InGame_min=1,m=2] Spell3 1200
replaceitem entity @a[score_Mana=49,score_Class_min=3,score_Class=3,score_InGame_min=1,score_Spell3=0,score_Spell3_min=0,m=2,score_EffSilence=0] slot.hotbar.3 dye 1 8 {display:{Name:"Not enough mana !"},ench:[{id:19,lvl:0}]}
scoreboard players remove @a[score_Class_min=3,score_Class=3,score_UsePotion_min=2,score_UsePotion=2] Mana 50
replaceitem entity @a[score_Mana=24,score_Class_min=3,score_Class=3,score_InGame_min=1,score_Spell2=0,score_Spell2_min=0,m=2,score_EffSilence=0] slot.hotbar.2 dye 1 8 {display:{Name:"Not enough mana !"},ench:[{id:19,lvl:0}]}
scoreboard players remove @a[score_Class_min=3,score_Class=3,score_UseCarrot_min=2,score_UseCarrot=2] Mana 25
replaceitem entity @a[score_EffNoMove=0,score_Mana=14,score_Class_min=3,score_Class=3,score_InGame_min=1,score_Spell1=0,score_Spell1_min=0,m=2,score_EffSilence=0] slot.hotbar.1 dye 1 8 {display:{Name:"Not enough mana !"},ench:[{id:19,lvl:0}]}
scoreboard players remove @a[score_Class_min=3,score_Class=3,score_UseFishing_min=2,score_UseFishing=2] Mana 15
replaceitem entity @a[score_Mana_min=15,score_InGame_min=1,score_EffSilence=0,score_EffNoMove=0,score_Spell1=0,score_Class_min=3,score_Class=3,m=2] slot.hotbar.1 minecraft:fishing_rod 1 0 {Unbreakable:1,ench:[{id:19,lvl:0}],display:{Name:"Electrical Speed  50✸  7s",Lore:["۞ 15 Mana","... 7s","","» Dash 1s","☀ Stun 1s ▢ Range 1","+ Mark Es ▢ Range 1"]},HideFlags:63}
replaceitem entity @a[score_Mana_min=25,score_InGame_min=1,score_EffSilence=0,score_Spell2=0,score_Class_min=3,score_Class=3,m=2] slot.hotbar.2 minecraft:carrot_on_a_stick 1 0 {Unbreakable:1,ench:[{id:19,lvl:0}],display:{Name:"Strike  25✸  5s",Lore:["۞ 25 Mana","... 5s","","⚔ 3 - 5 Damage ▢ All Es Marked","","+ Mark Es ▢ Lancable Range 3"]},HideFlags:63}
replaceitem entity @a[score_Mana_min=50,score_InGame_min=1,score_EffSilence=0,score_Spell3=0,score_Class_min=3,score_Class=3,m=2] slot.hotbar.3 minecraft:splash_potion 1 0 {Unbreakable:1,ench:[{id:19,lvl:0}],display:{Name:"Tempest  15✸  60s",Lore:["۞ 50 Mana","... 60s","","⚔ 3 - 25 Damage ▢ Area Range 7","☀ 2 Slow 1s ▢ Area Range 7","☀ No teleport ▢ Area Range 7"]},HideFlags:63}
execute @a[score_EffNoDie=0,score_IsDead_min=2,score_IsDead=2,score_InGame_min=1,score_TouchBy_min=3,score_TouchBy=3,team=Orange] ~ ~ ~ /say was electrocuted by @p[score_Class_min=3,score_Class=3,team=Blue,score_InGame_min=1]
execute @a[score_EffNoDie=0,score_IsDead_min=2,score_IsDead=2,score_InGame_min=1,score_TouchBy_min=3,score_TouchBy=3,team=Blue] ~ ~ ~ /say was electrocuted by @p[score_Class_min=3,score_Class=3,team=Orange,score_InGame_min=1]
execute @a[score_EffNoDie=0,score_IsDead_min=2,score_IsDead=2,score_InGame_min=1,score_TouchBy_min=3,score_TouchBy=3,team=Orange] ~ ~ ~ /scoreboard players add @p[score_Class_min=3,score_Class=3,team=Blue,score_InGame_min=1,tag=!InTraining] KillNumber 1
execute @a[score_EffNoDie=0,score_IsDead_min=2,score_IsDead=2,score_InGame_min=1,score_TouchBy_min=3,score_TouchBy=3,team=Blue] ~ ~ ~ /scoreboard players add @p[score_Class_min=3,score_Class=3,team=Orange,score_InGame_min=1,tag=!InTraining] KillNumber 1