# This file is automatically generated and will most likely be overwritten, do not edit it
scoreboard players set @s bs.block.type.id 0
execute if predicate bs.block:get/type/group_0 run scoreboard players add @s bs.block.type.id 1
execute if predicate bs.block:get/type/group_1 run scoreboard players add @s bs.block.type.id 2
execute if predicate bs.block:get/type/group_2 run scoreboard players add @s bs.block.type.id 4
execute if predicate bs.block:get/type/group_3 run scoreboard players add @s bs.block.type.id 8
execute if predicate bs.block:get/type/group_4 run scoreboard players add @s bs.block.type.id 16
execute if predicate bs.block:get/type/group_5 run scoreboard players add @s bs.block.type.id 32
execute if predicate bs.block:get/type/group_6 run scoreboard players add @s bs.block.type.id 64
execute if predicate bs.block:get/type/group_7 run scoreboard players add @s bs.block.type.id 128
execute if predicate bs.block:get/type/group_8 run scoreboard players add @s bs.block.type.id 256
execute if predicate bs.block:get/type/group_9 run scoreboard players add @s bs.block.type.id 512

function bs.block:get/type/from/score_id
