# This file is automatically generated and will most likely be overwritten, do not edit it
scoreboard players set @s bs.block_state.id 0
execute if predicate bs.block:get/block_state/group_0 run scoreboard players add @s bs.block_state.id 1
execute if predicate bs.block:get/block_state/group_1 run scoreboard players add @s bs.block_state.id 2
execute if predicate bs.block:get/block_state/group_2 run scoreboard players add @s bs.block_state.id 4
execute if predicate bs.block:get/block_state/group_3 run scoreboard players add @s bs.block_state.id 8
execute if predicate bs.block:get/block_state/group_4 run scoreboard players add @s bs.block_state.id 16
execute if predicate bs.block:get/block_state/group_5 run scoreboard players add @s bs.block_state.id 32
execute if predicate bs.block:get/block_state/group_6 run scoreboard players add @s bs.block_state.id 64
execute if predicate bs.block:get/block_state/group_7 run scoreboard players add @s bs.block_state.id 128
execute if predicate bs.block:get/block_state/group_8 run scoreboard players add @s bs.block_state.id 256
execute if predicate bs.block:get/block_state/group_9 run scoreboard players add @s bs.block_state.id 512
execute if predicate bs.block:get/block_state/group_10 run scoreboard players add @s bs.block_state.id 1024
execute if predicate bs.block:get/block_state/group_11 run scoreboard players add @s bs.block_state.id 2048
execute if predicate bs.block:get/block_state/group_12 run scoreboard players add @s bs.block_state.id 4096

function bs.block:block_state/from/score_id
