execute @a[score_Class_min=14,score_Class=14,score_Spell3_min=899,score_Spell3=899,team=Blue] ~ ~ ~ /summon Silverfish ~ ~ ~ {Tags:["143B","143G","Blue","NotOrange"]}
execute @e[type=Silverfish,tag=143B,score_Timer_min=-198,score_Timer=-198] ~ ~ ~ /scoreboard players set @e[r=10,team=!Blue] EffDamage 1003
execute @e[type=Silverfish,tag=143B] ~ ~ ~ /scoreboard players set @e[r=10,team=!Blue,score_EffPoison=1003] EffPoison 1003
execute @e[type=Silverfish,tag=143B] ~ ~ ~ /scoreboard players set @e[r=10,team=Orange,score_EffSlow=5] EffSlow 5
execute @e[type=Silverfish,tag=143B,score_Timer_min=-198,score_Timer=-198] ~ ~ ~ /scoreboard players set @e[r=10,team=Orange,score_EffSlow=3020] EffSlow 3020
execute @e[type=Silverfish,tag=143B] ~ ~ ~ /scoreboard players set @e[r=10,team=!Blue] TouchBy 14
execute @e[type=Silverfish,tag=143B,score_Timer_min=-101,score_Timer=-101] ~ ~ ~ /summon armor_stand ~ ~-71.5 ~ {NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Blue"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=Silverfish,tag=143B,score_Timer_min=-141,score_Timer=-141] ~ ~ ~ /summon armor_stand ~ ~-71.5 ~ {NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Blue"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=Silverfish,tag=143B,score_Timer_min=-181,score_Timer=-181] ~ ~ ~ /summon armor_stand ~ ~-71.5 ~ {NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Blue"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=Silverfish,tag=143G,score_Timer_min=-198,score_Timer=-198] ~ ~ ~ /playsound entity.generic.explode record @a[r=30] ~ ~ ~ 2 1 1
execute @e[type=Silverfish,tag=143G] ~ ~ ~ /particle fireworksSpark ~ ~0.5 ~ 8 0 8 0 1 force
scoreboard players set @e[type=Silverfish,tag=143G,score_Timer_min=-99] Timer -100
execute @a[score_Class_min=14,score_Class=14,score_Spell3_min=899,score_Spell3=899,team=Orange] ~ ~ ~ /summon Silverfish ~ ~ ~ {Tags:["143R","143G","Orange","NotBlue"]}
execute @e[type=Silverfish,tag=143R,score_Timer_min=-198,score_Timer=-198] ~ ~ ~ /scoreboard players set @e[r=10,team=Blue,score_EffSlow=3020] EffSlow 3020
execute @e[type=Silverfish,tag=143R] ~ ~ ~ /scoreboard players set @e[r=10,team=Blue,score_EffSlow=5] EffSlow 5
execute @e[type=Silverfish,tag=143R] ~ ~ ~ /scoreboard players set @e[r=10,team=!Orange,score_EffPoison=1003] EffPoison 1003
execute @e[type=Silverfish,tag=143R,score_Timer_min=-198,score_Timer=-198] ~ ~ ~ /scoreboard players set @e[r=10,team=!Orange] EffDamage 1003
execute @e[type=Silverfish,tag=143R] ~ ~ ~ /scoreboard players set @e[r=10,team=!Orange] TouchBy 14
execute @e[type=Silverfish,tag=143R,score_Timer_min=-101,score_Timer=-101] ~ ~ ~ /summon armor_stand ~ ~-71.5 ~ {NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Orange"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=Silverfish,tag=143R,score_Timer_min=-141,score_Timer=-141] ~ ~ ~ /summon armor_stand ~ ~-71.5 ~ {NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Orange"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}
execute @e[type=Silverfish,tag=143R,score_Timer_min=-181,score_Timer=-181] ~ ~ ~ /summon armor_stand ~ ~-71.5 ~ {NoGravity:1,Rotation:[180f],CustomName:RotBase,Tags:[“RotBase”,"Rot"],Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Start,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot"],CustomName:Middle,Passengers:[{id:armor_stand,Invisible:1,Tags:["Rot"]},{id:Boat,Rotation:[0f],Tags:["Rot","Orange"],CustomName:End}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}
execute @a[score_Class_min=14,score_Class=14,score_Spell2_min=298,team=Blue] ~ ~ ~ /scoreboard players set @e[team=!Blue,score_LifeState_min=500,r=7] EffDamage 3
execute @a[score_Class_min=14,score_Class=14,score_Spell2_min=298,team=Blue] ~ ~ ~ /scoreboard players set @e[team=Orange,r=7,score_LifeState_min=500,score_EffSlow=1060] EffSlow 1060
execute @a[score_Class_min=14,score_Class=14,score_Spell2_min=298,team=Blue] ~ ~ ~ /scoreboard players set @a[team=Orange,r=7,score_LifeState_min=500,score_EffSilence=60] EffSilence 60
execute @a[score_Class_min=14,score_Class=14,score_Spell2_min=298,team=Blue] ~ ~ ~ /scoreboard players set @e[team=!Blue,score_LifeState_min=500,r=7] TouchBy 14
execute @a[score_Class_min=14,score_Class=14,score_Spell2_min=299] ~ ~ ~ /playsound block.redstone_torch.burnout record @a[r=30] ~ ~ ~ 2 1 1
execute @a[score_Class_min=14,score_Class=14,score_Spell2_min=298,team=Orange] ~ ~ ~ /scoreboard players set @a[team=Blue,r=7,score_LifeState_min=500,score_EffSilence=60] EffSilence 60
execute @a[score_Class_min=14,score_Class=14,score_Spell2_min=298,team=Orange] ~ ~ ~ /scoreboard players set @e[team=Blue,r=7,score_LifeState_min=500,score_EffSlow=1060] EffSlow 1060
execute @a[score_Class_min=14,score_Class=14,score_Spell2_min=298,team=Orange] ~ ~ ~ /scoreboard players set @e[team=!Orange,r=7,score_LifeState_min=500] EffDamage 3
execute @a[score_Class_min=14,score_Class=14,score_Spell2_min=298,team=Orange] ~ ~ ~ /scoreboard players set @e[team=!Orange,r=7,score_LifeState_min=500] TouchBy 14
execute @a[score_Class_min=14,score_Class=14,score_Spell1_min=499] ~ ~ ~ /playsound block.water.ambient record @a[r=10] ~ ~ ~ 2 2 1
scoreboard players set @a[score_Class_min=14,score_Class=14,score_Spell1_min=499,score_EffSpeed=1080] EffSpeed 1080
scoreboard players set @a[score_Class_min=14,score_Class=14,score_Spell1_min=499,score_EffInvisibility=80] EffInvisibility 80
replaceitem entity @a[score_InGame_min=1,score_Class_min=14,score_Class=14,score_EffNoTp_min=1,score_Spell1=0,m=2] slot.hotbar.1 minecraft:barrier 1 0 {display:{Name:"Don't Move !"}}
execute @a[score_TouchBy_min=14,score_TouchBy=14,score_InGame_min=1,score_TakeDamage_min=2000,score_TakeDamage=2999,m=2,score_EffPoison_min=1] ~ ~ ~ /particle splash ~ ~1 ~ 0.5 1 0.5 0 40 force
execute @a[score_TouchBy_min=14,score_TouchBy=14,score_InGame_min=1,score_TakeDamage_min=2000,score_TakeDamage=2999,m=2,score_EffPoison_min=1] ~ ~ ~ /particle dripWater ~ ~1 ~ 0.5 1 0.5 0 20 force
scoreboard players set @a[score_Class_min=14,score_Class=14,score_UseTp_min=2,score_UseTp=2,score_InGame_min=1,m=2] Spell1 500
scoreboard players set @a[score_Class_min=14,score_Class=14,score_UseFishing_min=2,score_UseFishing=2,score_InGame_min=1,m=2] Spell2 300
scoreboard players set @a[score_Class_min=14,score_Class=14,score_UseXp_min=2,score_UseXp=2,score_InGame_min=1,m=2] Spell3 900
replaceitem entity @a[score_Mana=39,score_Class_min=14,score_Class=14,score_InGame_min=1,score_Spell1=0,score_Spell1_min=0,m=2,score_EffSilence=0] slot.hotbar.1 dye 1 8 {display:{Name:"Not enough mana !"},ench:[{id:19,lvl:0}]}
scoreboard players remove @a[score_Class_min=14,score_Class=14,score_UseTp_min=2,score_UseTp=2] Mana 40
replaceitem entity @a[score_Mana=24,score_Class_min=14,score_Class=14,score_InGame_min=1,score_Spell2=0,score_Spell2_min=0,m=2,score_EffSilence=0] slot.hotbar.2 dye 1 8 {display:{Name:"Not enough mana !"},ench:[{id:19,lvl:0}]}
scoreboard players remove @a[score_Class_min=14,score_Class=14,score_UseFishing_min=2,score_UseFishing=2] Mana 25
replaceitem entity @a[score_Mana=69,score_Class_min=14,score_Class=14,score_InGame_min=1,score_Spell3=0,score_Spell3_min=0,m=2,score_EffSilence=0] slot.hotbar.3 dye 1 8 {display:{Name:"Not enough mana !"},ench:[{id:19,lvl:0}]}
scoreboard players remove @a[score_Class_min=14,score_Class=14,score_UseXp_min=2,score_UseXp=2] Mana 70
replaceitem entity @a[score_Mana_min=40,score_InGame_min=1,score_EffSilence=0,score_EffNoTp=0,score_Spell1=0,score_Class_min=14,score_Class=14,m=2] slot.hotbar.1 minecraft:ender_pearl 1 0 {Unbreakable:1,ench:[{id:19,lvl:0}],display:{Name:"Transparency  40✸  25s"},HideFlags:63}
replaceitem entity @a[score_Mana_min=25,score_InGame_min=1,score_EffSilence=0,score_Spell2=0,score_Class_min=14,score_Class=14,m=2] slot.hotbar.2 minecraft:fishing_rod 1 0 {Unbreakable:1,ench:[{id:19,lvl:0}],display:{Name:"Winter Silence  25✸  15s"},HideFlags:63}
replaceitem entity @a[score_Mana_min=70,score_InGame_min=1,score_EffSilence=0,score_Spell3=0,score_Class_min=14,score_Class=14,m=2] slot.hotbar.3 minecraft:experience_bottle 1 0 {Unbreakable:1,ench:[{id:19,lvl:0}],display:{Name:"Cooling  70✸  45s"},HideFlags:63}
execute @a[score_EffNoDie=0,score_IsDead_min=2,score_IsDead=2,score_InGame_min=1,score_TouchBy_min=14,score_TouchBy=14,team=Orange] ~ ~ ~ /say is now an iceberg because of @p[score_Class_min=14,score_Class=14,team=Blue,score_InGame_min=1]
execute @a[score_EffNoDie=0,score_IsDead_min=2,score_IsDead=2,score_InGame_min=1,score_TouchBy_min=14,score_TouchBy=14,team=Blue] ~ ~ ~ /say is now an iceberg because of @p[score_Class_min=14,score_Class=14,team=Orange,score_InGame_min=1]
execute @a[score_EffNoDie=0,score_IsDead_min=2,score_IsDead=2,score_InGame_min=1,score_TouchBy_min=14,score_TouchBy=14,team=Orange] ~ ~ ~ /scoreboard players add @p[score_Class_min=14,score_Class=14,team=Blue,score_InGame_min=1,tag=!InTraining] KillNumber 1
execute @a[score_EffNoDie=0,score_IsDead_min=2,score_IsDead=2,score_InGame_min=1,score_TouchBy_min=14,score_TouchBy=14,team=Blue] ~ ~ ~ /scoreboard players add @p[score_Class_min=14,score_Class=14,team=Orange,score_InGame_min=1,tag=!InTraining] KillNumber 1