name: "📝 Other"
description: Submit any other suggestions, such as adding related tools to the documentation.
body:
  - type: textarea
    attributes:
      label: Suggestion or Inquiry
      description: |
        Please describe your suggestion, request, or inquiry:
        - What would you like to see added, improved, or clarified?
        - Include any relevant tools, examples, or links if applicable.
      placeholder: |
        Example:
        - Suggest adding a related tool to the documentation.
        - Request an update for clearer documentation on a specific feature.
    validations:
      required: true
