scoreboard objectives add Input1 dummy
scoreboard objectives add Input2 dummy
scoreboard objectives add Input3 dummy
scoreboard objectives add Input4 dummy
scoreboard objectives add Input5 dummy
scoreboard objectives add Input6 dummy
scoreboard objectives add Input7 dummy
scoreboard objectives add Input8 dummy
scoreboard objectives add Input9 dummy

scoreboard objectives add Tmp1 dummy
scoreboard objectives add Tmp2 dummy
scoreboard objectives add Tmp3 dummy
scoreboard objectives add Tmp4 dummy
scoreboard objectives add Tmp5 dummy
scoreboard objectives add Tmp6 dummy
scoreboard objectives add Tmp7 dummy
scoreboard objectives add Tmp8 dummy
scoreboard objectives add Tmp9 dummy

scoreboard objectives add Output1 dummy
scoreboard objectives add Output2 dummy
scoreboard objectives add Output3 dummy
scoreboard objectives add Output4 dummy
scoreboard objectives add Output5 dummy
scoreboard objectives add Output6 dummy
scoreboard objectives add Output7 dummy
scoreboard objectives add Output8 dummy
scoreboard objectives add Output9 dummy
