scoreboard objectives remove Var1
scoreboard objectives remove Var2
scoreboard objectives remove Var3
scoreboard objectives remove Var4
scoreboard objectives remove Var5
scoreboard objectives remove Var6
scoreboard objectives remove Var7
scoreboard objectives remove Var8
scoreboard objectives remove Var9
