scoreboard players reset @s Biome
advancement revoke @s only Gunivers-Lib:Advancements/Biome/Beaches
advancement revoke @s only Gunivers-Lib:Advancements/Biome/BirchForest
advancement revoke @s only Gunivers-Lib:Advancements/Biome/BirchForestHills
advancement revoke @s only Gunivers-Lib:Advancements/Biome/ColdBeach
advancement revoke @s only Gunivers-Lib:Advancements/Biome/DeepOcean
advancement revoke @s only Gunivers-Lib:Advancements/Biome/Desert
advancement revoke @s only Gunivers-Lib:Advancements/Biome/DesertHills
advancement revoke @s only Gunivers-Lib:Advancements/Biome/ExtremeHills
advancement revoke @s only Gunivers-Lib:Advancements/Biome/ExtremeHillsWithTrees
advancement revoke @s only Gunivers-Lib:Advancements/Biome/Forest
advancement revoke @s only Gunivers-Lib:Advancements/Biome/ForestHills
advancement revoke @s only Gunivers-Lib:Advancements/Biome/FrozenOcean
advancement revoke @s only Gunivers-Lib:Advancements/Biome/FrozenRiver
advancement revoke @s only Gunivers-Lib:Advancements/Biome/Hell
advancement revoke @s only Gunivers-Lib:Advancements/Biome/IceFlats
advancement revoke @s only Gunivers-Lib:Advancements/Biome/IceMountains
advancement revoke @s only Gunivers-Lib:Advancements/Biome/Jungle
advancement revoke @s only Gunivers-Lib:Advancements/Biome/JungleEdge
advancement revoke @s only Gunivers-Lib:Advancements/Biome/JungleHills
advancement revoke @s only Gunivers-Lib:Advancements/Biome/Mesa
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MesaClearRock
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MesaRock
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MushroomIsland
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MushroomIslandShore
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedBirchForest
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedBirchForestHills
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedDesert
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedExtremeHills
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedForest
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedIceFlats
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedJungle
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedJungleEdge
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedMesa
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedMesaRock
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedMesaRockClearRock
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedPlain
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedRedwoodTaiga
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedRedwoodTaigaHills
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedRedwoodTaigaHillsWithTrees
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedRoofedForest
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedSavanna
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedSavannaRock
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedSwampland
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedTaiga
advancement revoke @s only Gunivers-Lib:Advancements/Biome/MutatedTaigaCold
advancement revoke @s only Gunivers-Lib:Advancements/Biome/Ocean
advancement revoke @s only Gunivers-Lib:Advancements/Biome/Plains
advancement revoke @s only Gunivers-Lib:Advancements/Biome/RedwoodTaiga
advancement revoke @s only Gunivers-Lib:Advancements/Biome/RedwoodTaigaHills
advancement revoke @s only Gunivers-Lib:Advancements/Biome/River
advancement revoke @s only Gunivers-Lib:Advancements/Biome/RoofedForest
advancement revoke @s only Gunivers-Lib:Advancements/Biome/Savanna
advancement revoke @s only Gunivers-Lib:Advancements/Biome/SavannaRock
advancement revoke @s only Gunivers-Lib:Advancements/Biome/Sky
advancement revoke @s only Gunivers-Lib:Advancements/Biome/SmallerExtremeHills
advancement revoke @s only Gunivers-Lib:Advancements/Biome/StoneBeach
advancement revoke @s only Gunivers-Lib:Advancements/Biome/Swampland
advancement revoke @s only Gunivers-Lib:Advancements/Biome/Taiga
advancement revoke @s only Gunivers-Lib:Advancements/Biome/TaigaCold
advancement revoke @s only Gunivers-Lib:Advancements/Biome/TaigaColdHills
advancement revoke @s only Gunivers-Lib:Advancements/Biome/TaigaHills
advancement revoke @s only Gunivers-Lib:Advancements/Biome/Void
advancement revoke @s only Gunivers-Lib:Advancements/Biome/Swampland