scoreboard players enable @a Menu
effect @a[score_Menu=-1] glowing 1 0 true
execute @a[team=Blue,score_Menu=-1] ~ ~ ~ execute @a[team=Blue] ~ ~ ~ playsound block.note.snare record @p[r=1] ~ ~ ~ 2 2 1
execute @a[team=Orange,score_Menu=-1] ~ ~ ~ execute @a[team=Orange] ~ ~ ~ playsound block.note.snare record @p[r=1] ~ ~ ~ 2 2 1
execute @a[score_Menu_min=-5,score_Menu=-5,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": I need help !","color":"green"}] 
execute @a[score_Menu_min=-5,score_Menu=-5,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": I need help !","color":"green"}] 
execute @a[score_Menu_min=-10,score_Menu=-10,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Attack !","color":"green"}] 
execute @a[score_Menu_min=-10,score_Menu=-10,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Attack !","color":"green"}] 
execute @a[score_Menu_min=-15,score_Menu=-15,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Attack left lane !","color":"green"}] 
execute @a[score_Menu_min=-15,score_Menu=-15,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Attack left lane !","color":"green"}] 
execute @a[score_Menu_min=-20,score_Menu=-20,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Attack right lane !","color":"green"}] 
execute @a[score_Menu_min=-20,score_Menu=-20,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Attack right lane !","color":"green"}] 
execute @a[score_Menu_min=-25,score_Menu=-25,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Attack middle lane !","color":"green"}] 
execute @a[score_Menu_min=-25,score_Menu=-25,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Attack middle lane !","color":"green"}] 
execute @a[score_Menu_min=-30,score_Menu=-30,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Gank !","color":"green"}] 
execute @a[score_Menu_min=-30,score_Menu=-30,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Gank !","color":"green"}] 
execute @a[score_Menu_min=-35,score_Menu=-35,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Take this bonus !","color":"green"}] 
execute @a[score_Menu_min=-35,score_Menu=-35,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Take this bonus !","color":"green"}] 
execute @a[score_Menu_min=-40,score_Menu=-40,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Follow me !","color":"green"}] 
execute @a[score_Menu_min=-40,score_Menu=-40,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Follow me !","color":"green"}] 
execute @a[score_Menu_min=-45,score_Menu=-45,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Defend !","color":"green"}] 
execute @a[score_Menu_min=-45,score_Menu=-45,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Defend !","color":"green"}] 
execute @a[score_Menu_min=-50,score_Menu=-50,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Defend left lane !","color":"green"}] 
execute @a[score_Menu_min=-50,score_Menu=-50,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Defend left lane !","color":"green"}] 
execute @a[score_Menu_min=-55,score_Menu=-55,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Defend right lane !","color":"green"}] 
execute @a[score_Menu_min=-55,score_Menu=-55,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Defend right lane !","color":"green"}] 
execute @a[score_Menu_min=-60,score_Menu=-60,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Defend middle lane !","color":"green"}] 
execute @a[score_Menu_min=-60,score_Menu=-60,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Defend middle lane !","color":"green"}] 
execute @a[score_Menu_min=-65,score_Menu=-65,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Be carefull !","color":"green"}] 
execute @a[score_Menu_min=-65,score_Menu=-65,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Be carefull !","color":"green"}] 
execute @a[score_Menu_min=-70,score_Menu=-70,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Retreat !","color":"green"}] 
execute @a[score_Menu_min=-70,score_Menu=-70,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Retreat !","color":"green"}] 
execute @a[score_Menu_min=-75,score_Menu=-75,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Enemies missing !","color":"green"}] 
execute @a[score_Menu_min=-75,score_Menu=-75,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Enemies missing !","color":"green"}] 
execute @a[score_Menu_min=-80,score_Menu=-80,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Ennemis on the left !","color":"green"}] 
execute @a[score_Menu_min=-80,score_Menu=-80,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Ennemis on the left !","color":"green"}] 
execute @a[score_Menu_min=-85,score_Menu=-85,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Ennemis on the right !","color":"green"}] 
execute @a[score_Menu_min=-85,score_Menu=-85,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Ennemis on the right !","color":"green"}] 
execute @a[score_Menu_min=-90,score_Menu=-90,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Behind us !","color":"green"}] 
execute @a[score_Menu_min=-90,score_Menu=-90,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Behind us !","color":"green"}] 
execute @a[score_Menu_min=-95,score_Menu=-95,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Yes !","color":"green"}] 
execute @a[score_Menu_min=-95,score_Menu=-95,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Yes !","color":"green"}] 
execute @a[score_Menu_min=-100,score_Menu=-100,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": No !","color":"green"}] 
execute @a[score_Menu_min=-100,score_Menu=-100,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": No !","color":"green"}] 
execute @a[score_Menu_min=-105,score_Menu=-105,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Thanks !","color":"green"}] 
execute @a[score_Menu_min=-105,score_Menu=-105,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Thanks !","color":"green"}] 
execute @a[score_Menu_min=-110,score_Menu=-110,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Sorry !","color":"green"}] 
execute @a[score_Menu_min=-110,score_Menu=-110,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Sorry !","color":"green"}] 
execute @a[score_Menu_min=-115,score_Menu=-115,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Awsome !","color":"green"}] 
execute @a[score_Menu_min=-115,score_Menu=-115,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Awsome !","color":"green"}] 
execute @a[score_Menu_min=-120,score_Menu=-120,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": That's too bad !","color":"green"}] 
execute @a[score_Menu_min=-120,score_Menu=-120,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": That's too bad !","color":"green"}] 
execute @a[score_Menu_min=-125,score_Menu=-125,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": No problems !","color":"green"}] 
execute @a[score_Menu_min=-125,score_Menu=-125,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": No problems !","color":"green"}] 
execute @a[score_Menu_min=-130,score_Menu=-130,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Oups !","color":"green"}] 
execute @a[score_Menu_min=-130,score_Menu=-130,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Oups !","color":"green"}] 
execute @a[score_Menu_min=-135,score_Menu=-135,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Woohoo !","color":"green"}] 
execute @a[score_Menu_min=-135,score_Menu=-135,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Woohoo !","color":"green"}] 
execute @a[score_Menu_min=-140,score_Menu=-140,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Good game !","color":"green"}] 
execute @a[score_Menu_min=-140,score_Menu=-140,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Good game !","color":"green"}] 
execute @a[score_Menu_min=-145,score_Menu=-145,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Ha ha ha ha !","color":"green"}] 
execute @a[score_Menu_min=-145,score_Menu=-145,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Ha ha ha ha !","color":"green"}] 
execute @a[score_Back=23,score_Back_min=20,team=Blue] ~ ~ ~ execute @a[team=Blue] ~ ~ ~ playsound note.snare @p ~ ~ ~ 2 1 1
execute @a[score_Back=23,score_Back_min=20,team=Orange] ~ ~ ~ execute @a[team=Orange] ~ ~ ~ playsound note.snare @p ~ ~ ~ 2 1 1
execute @a[score_Back_min=20,score_Back=20,team=Blue] ~ ~ ~ tellraw @a[team=Blue] ["",{"selector":"@p"},{"text":": Be right back !","color":"green"}] 
execute @a[score_Back_min=20,score_Back=20,team=Orange] ~ ~ ~ tellraw @a[team=Orange] ["",{"selector":"@p"},{"text":": Be right back !","color":"green"}] 
scoreboard players set @a[score_Menu=-1] Menu 0