scoreboard players tag @a remove InTraining
scoreboard players tag @a[x=2000,y=100,z=2000,r=50] add InTraining
scoreboard players tag * remove AffectByBlue
scoreboard players tag @e[tag=IsPlaying,team=Orange] add AffectByBlue
scoreboard players tag * remove AffectByOrange
scoreboard players tag @e[tag=IsPlaying,team=Blue] add AffectByOrange
scoreboard players tag * remove IsPlaying
scoreboard players tag @a[score_InGame_min=1,score_Class_min=1,team=Blue,m=2] add IsPlaying
scoreboard players tag @a[score_InGame_min=1,score_Class_min=1,team=Orange,m=2] add IsPlaying
scoreboard players tag @e[type=Skeleton] add IsPlaying
scoreboard players tag @e[type=Zombie] add IsPlaying
scoreboard players tag @e[type=Spider] add IsPlaying
scoreboard players tag @e[type=Ocelot] add IsPlaying