effect @a[score_EffRegen_min=1,score_EffRegen=999,score_Timer_min=21,score_Timer=21,tag=IsPlaying] regeneration 1 2 true
effect @a[score_EffRegen_min=1,score_EffRegen=999,score_Timer_min=31,score_Timer=31,tag=IsPlaying] regeneration 1 2 true
effect @a[score_EffRegen_min=1,score_EffRegen=999,score_Timer_min=11,score_Timer=11,tag=IsPlaying] regeneration 1 2 true
effect @a[score_EffRegen_min=1,score_EffRegen=999,score_Timer_min=1,score_Timer=1,tag=IsPlaying] regeneration 1 2 true
effect @a[score_EffRegen_min=1000,score_Timer_min=21,score_Timer=21,tag=IsPlaying] regeneration 1 3 true
effect @a[score_EffRegen_min=1000,score_Timer_min=31,score_Timer=31,tag=IsPlaying] regeneration 1 3 true
effect @a[score_EffRegen_min=1000,score_Timer_min=1,score_Timer=1,tag=IsPlaying] regeneration 1 3 true
effect @a[score_EffRegen_min=1000,score_Timer_min=11,score_Timer=11,tag=IsPlaying] regeneration 1 3 true
scoreboard players set @e[score_EffRegen_min=1000,score_EffRegen=1000] EffRegen 0
scoreboard players remove @e[score_EffRegen_min=1] EffRegen 1