scoreboard players set @a[score_EffSlow_min=3000,score_EffNoTp=2] EffNoTp 2
scoreboard players set @a[score_EffSlow_min=3000,score_EffNoMove=2] EffNoMove 2
effect @e[score_EffSlow_min=1,score_EffSlow=999,tag=IsPlaying] slowness 1 0 true
effect @e[score_EffSlow_min=1000,score_EffSlow=1999,tag=IsPlaying] slowness 1 1 true
effect @e[score_EffSlow_min=2000,score_EffSlow=2999,tag=IsPlaying] slowness 1 2 true
effect @e[score_EffSlow_min=3000,score_EffSlow=3999,tag=IsPlaying] slowness 1 100 true
scoreboard players set @e[score_EffSlow_min=1000,score_EffSlow=1000] EffSlow 0
scoreboard players set @e[score_EffSlow_min=2000,score_EffSlow=2000] EffSlow 0
scoreboard players set @e[score_EffSlow_min=3000,score_EffSlow=3000] EffSlow 0
scoreboard players remove @e[score_EffSlow_min=1] EffSlow 1
