scoreboard objectives add Cache dummy
scoreboard objectives add CacheOffsetX dummy
scoreboard objectives add CacheOffsetZ dummy
scoreboard players set 0 Cache 0
scoreboard players set 0 CacheOffsetX 0
scoreboard players set 0 CacheOffsetZ 12
scoreboard players set 1 Cache 0
scoreboard players set 1 CacheOffsetX 0
scoreboard players set 1 CacheOffsetZ 11
scoreboard players set 2 Cache 0
scoreboard players set 2 CacheOffsetX 0
scoreboard players set 2 CacheOffsetZ 10
scoreboard players set 3 Cache 0
scoreboard players set 3 CacheOffsetX 0
scoreboard players set 3 CacheOffsetZ 9
scoreboard players set 4 Cache 0
scoreboard players set 4 CacheOffsetX 0
scoreboard players set 4 CacheOffsetZ 8
scoreboard players set 5 Cache 0
scoreboard players set 5 CacheOffsetX 0
scoreboard players set 5 CacheOffsetZ 7
scoreboard players set 6 Cache 0
scoreboard players set 6 CacheOffsetX 0
scoreboard players set 6 CacheOffsetZ 6
scoreboard players set 7 Cache 0
scoreboard players set 7 CacheOffsetX 0
scoreboard players set 7 CacheOffsetZ 5
scoreboard players set 8 Cache 0
scoreboard players set 8 CacheOffsetX 0
scoreboard players set 8 CacheOffsetZ 4
scoreboard players set 9 Cache 0
scoreboard players set 9 CacheOffsetX 0
scoreboard players set 9 CacheOffsetZ 3
scoreboard players set 10 Cache 0
scoreboard players set 10 CacheOffsetX 0
scoreboard players set 10 CacheOffsetZ 2
scoreboard players set 11 Cache 0
scoreboard players set 11 CacheOffsetX 0
scoreboard players set 11 CacheOffsetZ 1