# This file is automatically generated and will most likely be overwritten, do not edit it

  data modify storage bs:block types set value [ \
    { \
      name: "minecraft:air", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:stone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:granite", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:polished_granite", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:diorite", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:polished_diorite", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:andesite", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:polished_andesite", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:grass_block", \
      block_states_group: 59 \
    }, \
    { \
      name: "minecraft:dirt", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:coarse_dirt", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:podzol", \
      block_states_group: 59 \
    }, \
    { \
      name: "minecraft:cobblestone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:oak_planks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:spruce_planks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:birch_planks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:jungle_planks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:acacia_planks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cherry_planks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:dark_oak_planks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:mangrove_planks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:bamboo_planks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:bamboo_mosaic", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:oak_sapling", \
      block_states_group: 9 \
    }, \
    { \
      name: "minecraft:spruce_sapling", \
      block_states_group: 9 \
    }, \
    { \
      name: "minecraft:birch_sapling", \
      block_states_group: 9 \
    }, \
    { \
      name: "minecraft:jungle_sapling", \
      block_states_group: 9 \
    }, \
    { \
      name: "minecraft:acacia_sapling", \
      block_states_group: 9 \
    }, \
    { \
      name: "minecraft:cherry_sapling", \
      block_states_group: 9 \
    }, \
    { \
      name: "minecraft:dark_oak_sapling", \
      block_states_group: 9 \
    }, \
    { \
      name: "minecraft:mangrove_propagule", \
      block_states_group: 72 \
    }, \
    { \
      name: "minecraft:bedrock", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:water", \
      block_states_group: 68 \
    }, \
    { \
      name: "minecraft:lava", \
      block_states_group: 68 \
    }, \
    { \
      name: "minecraft:sand", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:suspicious_sand", \
      block_states_group: 96 \
    }, \
    { \
      name: "minecraft:red_sand", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:gravel", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:suspicious_gravel", \
      block_states_group: 96 \
    }, \
    { \
      name: "minecraft:gold_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:deepslate_gold_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:iron_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:deepslate_iron_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:coal_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:deepslate_coal_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:nether_gold_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:oak_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:spruce_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:birch_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:jungle_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:acacia_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:cherry_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:dark_oak_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:mangrove_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:mangrove_roots", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:muddy_mangrove_roots", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:bamboo_block", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_spruce_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_birch_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_jungle_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_acacia_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_cherry_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_dark_oak_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_oak_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_mangrove_log", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_bamboo_block", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:oak_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:spruce_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:birch_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:jungle_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:acacia_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:cherry_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:dark_oak_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:mangrove_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_oak_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_spruce_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_birch_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_jungle_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_acacia_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_cherry_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_dark_oak_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_mangrove_wood", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:oak_leaves", \
      block_states_group: 5 \
    }, \
    { \
      name: "minecraft:spruce_leaves", \
      block_states_group: 5 \
    }, \
    { \
      name: "minecraft:birch_leaves", \
      block_states_group: 5 \
    }, \
    { \
      name: "minecraft:jungle_leaves", \
      block_states_group: 5 \
    }, \
    { \
      name: "minecraft:acacia_leaves", \
      block_states_group: 5 \
    }, \
    { \
      name: "minecraft:cherry_leaves", \
      block_states_group: 5 \
    }, \
    { \
      name: "minecraft:dark_oak_leaves", \
      block_states_group: 5 \
    }, \
    { \
      name: "minecraft:mangrove_leaves", \
      block_states_group: 5 \
    }, \
    { \
      name: "minecraft:azalea_leaves", \
      block_states_group: 5 \
    }, \
    { \
      name: "minecraft:flowering_azalea_leaves", \
      block_states_group: 5 \
    }, \
    { \
      name: "minecraft:sponge", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:wet_sponge", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:lapis_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:deepslate_lapis_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:lapis_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:dispenser", \
      block_states_group: 54 \
    }, \
    { \
      name: "minecraft:sandstone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:chiseled_sandstone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cut_sandstone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:note_block", \
      block_states_group: 75 \
    }, \
    { \
      name: "minecraft:white_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:orange_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:magenta_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:light_blue_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:yellow_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:lime_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:pink_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:gray_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:light_gray_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:cyan_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:purple_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:blue_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:brown_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:green_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:red_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:black_bed", \
      block_states_group: 27 \
    }, \
    { \
      name: "minecraft:powered_rail", \
      block_states_group: 15 \
    }, \
    { \
      name: "minecraft:detector_rail", \
      block_states_group: 15 \
    }, \
    { \
      name: "minecraft:sticky_piston", \
      block_states_group: 78 \
    }, \
    { \
      name: "minecraft:cobweb", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:grass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:fern", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:dead_bush", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:seagrass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:tall_seagrass", \
      block_states_group: 67 \
    }, \
    { \
      name: "minecraft:piston", \
      block_states_group: 78 \
    }, \
    { \
      name: "minecraft:piston_head", \
      block_states_group: 79 \
    }, \
    { \
      name: "minecraft:white_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:orange_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:magenta_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:light_blue_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:yellow_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:lime_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:pink_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:gray_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:light_gray_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cyan_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:purple_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:blue_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:brown_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:green_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:red_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:black_wool", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:moving_piston", \
      block_states_group: 73 \
    }, \
    { \
      name: "minecraft:dandelion", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:torchflower", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:poppy", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:blue_orchid", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:allium", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:azure_bluet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:red_tulip", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:orange_tulip", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:white_tulip", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:pink_tulip", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:oxeye_daisy", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cornflower", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:wither_rose", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:lily_of_the_valley", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:brown_mushroom", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:red_mushroom", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:gold_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:iron_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:tnt", \
      block_states_group: 97 \
    }, \
    { \
      name: "minecraft:bookshelf", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:chiseled_bookshelf", \
      block_states_group: 45 \
    }, \
    { \
      name: "minecraft:mossy_cobblestone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:obsidian", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:torch", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:wall_torch", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:fire", \
      block_states_group: 57 \
    }, \
    { \
      name: "minecraft:soul_fire", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:spawner", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:oak_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:chest", \
      block_states_group: 44 \
    }, \
    { \
      name: "minecraft:redstone_wire", \
      block_states_group: 84 \
    }, \
    { \
      name: "minecraft:diamond_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:deepslate_diamond_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:diamond_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:crafting_table", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:wheat", \
      block_states_group: 39 \
    }, \
    { \
      name: "minecraft:farmland", \
      block_states_group: 56 \
    }, \
    { \
      name: "minecraft:furnace", \
      block_states_group: 31 \
    }, \
    { \
      name: "minecraft:oak_sign", \
      block_states_group: 10 \
    }, \
    { \
      name: "minecraft:spruce_sign", \
      block_states_group: 10 \
    }, \
    { \
      name: "minecraft:birch_sign", \
      block_states_group: 10 \
    }, \
    { \
      name: "minecraft:acacia_sign", \
      block_states_group: 10 \
    }, \
    { \
      name: "minecraft:cherry_sign", \
      block_states_group: 10 \
    }, \
    { \
      name: "minecraft:jungle_sign", \
      block_states_group: 10 \
    }, \
    { \
      name: "minecraft:dark_oak_sign", \
      block_states_group: 10 \
    }, \
    { \
      name: "minecraft:mangrove_sign", \
      block_states_group: 10 \
    }, \
    { \
      name: "minecraft:bamboo_sign", \
      block_states_group: 10 \
    }, \
    { \
      name: "minecraft:oak_door", \
      block_states_group: 1 \
    }, \
    { \
      name: "minecraft:ladder", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:rail", \
      block_states_group: 83 \
    }, \
    { \
      name: "minecraft:cobblestone_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:oak_wall_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:spruce_wall_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:birch_wall_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:acacia_wall_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:cherry_wall_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:jungle_wall_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:dark_oak_wall_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:mangrove_wall_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:bamboo_wall_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:oak_hanging_sign", \
      block_states_group: 4 \
    }, \
    { \
      name: "minecraft:spruce_hanging_sign", \
      block_states_group: 4 \
    }, \
    { \
      name: "minecraft:birch_hanging_sign", \
      block_states_group: 4 \
    }, \
    { \
      name: "minecraft:acacia_hanging_sign", \
      block_states_group: 4 \
    }, \
    { \
      name: "minecraft:cherry_hanging_sign", \
      block_states_group: 4 \
    }, \
    { \
      name: "minecraft:jungle_hanging_sign", \
      block_states_group: 4 \
    }, \
    { \
      name: "minecraft:dark_oak_hanging_sign", \
      block_states_group: 4 \
    }, \
    { \
      name: "minecraft:crimson_hanging_sign", \
      block_states_group: 4 \
    }, \
    { \
      name: "minecraft:warped_hanging_sign", \
      block_states_group: 4 \
    }, \
    { \
      name: "minecraft:mangrove_hanging_sign", \
      block_states_group: 4 \
    }, \
    { \
      name: "minecraft:bamboo_hanging_sign", \
      block_states_group: 4 \
    }, \
    { \
      name: "minecraft:oak_wall_hanging_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:spruce_wall_hanging_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:birch_wall_hanging_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:acacia_wall_hanging_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:cherry_wall_hanging_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:jungle_wall_hanging_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:dark_oak_wall_hanging_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:mangrove_wall_hanging_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:crimson_wall_hanging_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:warped_wall_hanging_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:bamboo_wall_hanging_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:lever", \
      block_states_group: 0 \
    }, \
    { \
      name: "minecraft:stone_pressure_plate", \
      block_states_group: 8 \
    }, \
    { \
      name: "minecraft:iron_door", \
      block_states_group: 1 \
    }, \
    { \
      name: "minecraft:oak_pressure_plate", \
      block_states_group: 8 \
    }, \
    { \
      name: "minecraft:spruce_pressure_plate", \
      block_states_group: 8 \
    }, \
    { \
      name: "minecraft:birch_pressure_plate", \
      block_states_group: 8 \
    }, \
    { \
      name: "minecraft:jungle_pressure_plate", \
      block_states_group: 8 \
    }, \
    { \
      name: "minecraft:acacia_pressure_plate", \
      block_states_group: 8 \
    }, \
    { \
      name: "minecraft:cherry_pressure_plate", \
      block_states_group: 8 \
    }, \
    { \
      name: "minecraft:dark_oak_pressure_plate", \
      block_states_group: 8 \
    }, \
    { \
      name: "minecraft:mangrove_pressure_plate", \
      block_states_group: 8 \
    }, \
    { \
      name: "minecraft:bamboo_pressure_plate", \
      block_states_group: 8 \
    }, \
    { \
      name: "minecraft:redstone_ore", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:deepslate_redstone_ore", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:redstone_torch", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:redstone_wall_torch", \
      block_states_group: 31 \
    }, \
    { \
      name: "minecraft:stone_button", \
      block_states_group: 0 \
    }, \
    { \
      name: "minecraft:snow", \
      block_states_group: 94 \
    }, \
    { \
      name: "minecraft:ice", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:snow_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cactus", \
      block_states_group: 35 \
    }, \
    { \
      name: "minecraft:clay", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:sugar_cane", \
      block_states_group: 35 \
    }, \
    { \
      name: "minecraft:jukebox", \
      block_states_group: 64 \
    }, \
    { \
      name: "minecraft:oak_fence", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:pumpkin", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:netherrack", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:soul_sand", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:soul_soil", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:basalt", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:polished_basalt", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:soul_torch", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:soul_wall_torch", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:glowstone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:nether_portal", \
      block_states_group: 74 \
    }, \
    { \
      name: "minecraft:carved_pumpkin", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:jack_o_lantern", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:cake", \
      block_states_group: 36 \
    }, \
    { \
      name: "minecraft:repeater", \
      block_states_group: 85 \
    }, \
    { \
      name: "minecraft:white_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:orange_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:magenta_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:light_blue_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:yellow_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:lime_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:pink_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:gray_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:light_gray_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cyan_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:purple_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:blue_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:brown_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:green_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:red_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:black_stained_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:oak_trapdoor", \
      block_states_group: 13 \
    }, \
    { \
      name: "minecraft:spruce_trapdoor", \
      block_states_group: 13 \
    }, \
    { \
      name: "minecraft:birch_trapdoor", \
      block_states_group: 13 \
    }, \
    { \
      name: "minecraft:jungle_trapdoor", \
      block_states_group: 13 \
    }, \
    { \
      name: "minecraft:acacia_trapdoor", \
      block_states_group: 13 \
    }, \
    { \
      name: "minecraft:cherry_trapdoor", \
      block_states_group: 13 \
    }, \
    { \
      name: "minecraft:dark_oak_trapdoor", \
      block_states_group: 13 \
    }, \
    { \
      name: "minecraft:mangrove_trapdoor", \
      block_states_group: 13 \
    }, \
    { \
      name: "minecraft:bamboo_trapdoor", \
      block_states_group: 13 \
    }, \
    { \
      name: "minecraft:stone_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:mossy_stone_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cracked_stone_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:chiseled_stone_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:packed_mud", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:mud_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:infested_stone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:infested_cobblestone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:infested_stone_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:infested_mossy_stone_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:infested_cracked_stone_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:infested_chiseled_stone_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:brown_mushroom_block", \
      block_states_group: 33 \
    }, \
    { \
      name: "minecraft:red_mushroom_block", \
      block_states_group: 33 \
    }, \
    { \
      name: "minecraft:mushroom_stem", \
      block_states_group: 33 \
    }, \
    { \
      name: "minecraft:iron_bars", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:chain", \
      block_states_group: 42 \
    }, \
    { \
      name: "minecraft:glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:melon", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:attached_pumpkin_stem", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:attached_melon_stem", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:pumpkin_stem", \
      block_states_group: 39 \
    }, \
    { \
      name: "minecraft:melon_stem", \
      block_states_group: 39 \
    }, \
    { \
      name: "minecraft:vine", \
      block_states_group: 102 \
    }, \
    { \
      name: "minecraft:glow_lichen", \
      block_states_group: 58 \
    }, \
    { \
      name: "minecraft:oak_fence_gate", \
      block_states_group: 3 \
    }, \
    { \
      name: "minecraft:brick_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:stone_brick_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:mud_brick_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:mycelium", \
      block_states_group: 59 \
    }, \
    { \
      name: "minecraft:lily_pad", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:nether_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:nether_brick_fence", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:nether_brick_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:nether_wart", \
      block_states_group: 23 \
    }, \
    { \
      name: "minecraft:enchanting_table", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:brewing_stand", \
      block_states_group: 32 \
    }, \
    { \
      name: "minecraft:cauldron", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:water_cauldron", \
      block_states_group: 82 \
    }, \
    { \
      name: "minecraft:lava_cauldron", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:powder_snow_cauldron", \
      block_states_group: 82 \
    }, \
    { \
      name: "minecraft:end_portal", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:end_portal_frame", \
      block_states_group: 55 \
    }, \
    { \
      name: "minecraft:end_stone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:dragon_egg", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:redstone_lamp", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:cocoa", \
      block_states_group: 47 \
    }, \
    { \
      name: "minecraft:sandstone_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:emerald_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:deepslate_emerald_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:ender_chest", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:tripwire_hook", \
      block_states_group: 100 \
    }, \
    { \
      name: "minecraft:tripwire", \
      block_states_group: 99 \
    }, \
    { \
      name: "minecraft:emerald_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:spruce_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:birch_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:jungle_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:command_block", \
      block_states_group: 43 \
    }, \
    { \
      name: "minecraft:beacon", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cobblestone_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:mossy_cobblestone_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:flower_pot", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_torchflower", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_oak_sapling", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_spruce_sapling", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_birch_sapling", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_jungle_sapling", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_acacia_sapling", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_cherry_sapling", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_dark_oak_sapling", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_mangrove_propagule", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_fern", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_dandelion", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_poppy", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_blue_orchid", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_allium", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_azure_bluet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_red_tulip", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_orange_tulip", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_white_tulip", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_pink_tulip", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_oxeye_daisy", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_cornflower", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_lily_of_the_valley", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_wither_rose", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_red_mushroom", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_brown_mushroom", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_dead_bush", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_cactus", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:carrots", \
      block_states_group: 39 \
    }, \
    { \
      name: "minecraft:potatoes", \
      block_states_group: 39 \
    }, \
    { \
      name: "minecraft:oak_button", \
      block_states_group: 0 \
    }, \
    { \
      name: "minecraft:spruce_button", \
      block_states_group: 0 \
    }, \
    { \
      name: "minecraft:birch_button", \
      block_states_group: 0 \
    }, \
    { \
      name: "minecraft:jungle_button", \
      block_states_group: 0 \
    }, \
    { \
      name: "minecraft:acacia_button", \
      block_states_group: 0 \
    }, \
    { \
      name: "minecraft:cherry_button", \
      block_states_group: 0 \
    }, \
    { \
      name: "minecraft:dark_oak_button", \
      block_states_group: 0 \
    }, \
    { \
      name: "minecraft:mangrove_button", \
      block_states_group: 0 \
    }, \
    { \
      name: "minecraft:bamboo_button", \
      block_states_group: 0 \
    }, \
    { \
      name: "minecraft:skeleton_skull", \
      block_states_group: 50 \
    }, \
    { \
      name: "minecraft:skeleton_wall_skull", \
      block_states_group: 51 \
    }, \
    { \
      name: "minecraft:wither_skeleton_skull", \
      block_states_group: 50 \
    }, \
    { \
      name: "minecraft:wither_skeleton_wall_skull", \
      block_states_group: 51 \
    }, \
    { \
      name: "minecraft:zombie_head", \
      block_states_group: 50 \
    }, \
    { \
      name: "minecraft:zombie_wall_head", \
      block_states_group: 51 \
    }, \
    { \
      name: "minecraft:player_head", \
      block_states_group: 50 \
    }, \
    { \
      name: "minecraft:player_wall_head", \
      block_states_group: 51 \
    }, \
    { \
      name: "minecraft:creeper_head", \
      block_states_group: 50 \
    }, \
    { \
      name: "minecraft:creeper_wall_head", \
      block_states_group: 51 \
    }, \
    { \
      name: "minecraft:dragon_head", \
      block_states_group: 50 \
    }, \
    { \
      name: "minecraft:dragon_wall_head", \
      block_states_group: 51 \
    }, \
    { \
      name: "minecraft:piglin_head", \
      block_states_group: 50 \
    }, \
    { \
      name: "minecraft:piglin_wall_head", \
      block_states_group: 51 \
    }, \
    { \
      name: "minecraft:anvil", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:chipped_anvil", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:damaged_anvil", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:trapped_chest", \
      block_states_group: 44 \
    }, \
    { \
      name: "minecraft:light_weighted_pressure_plate", \
      block_states_group: 61 \
    }, \
    { \
      name: "minecraft:heavy_weighted_pressure_plate", \
      block_states_group: 61 \
    }, \
    { \
      name: "minecraft:comparator", \
      block_states_group: 48 \
    }, \
    { \
      name: "minecraft:daylight_detector", \
      block_states_group: 52 \
    }, \
    { \
      name: "minecraft:redstone_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:nether_quartz_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:hopper", \
      block_states_group: 62 \
    }, \
    { \
      name: "minecraft:quartz_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:chiseled_quartz_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:quartz_pillar", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:quartz_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:activator_rail", \
      block_states_group: 15 \
    }, \
    { \
      name: "minecraft:dropper", \
      block_states_group: 54 \
    }, \
    { \
      name: "minecraft:white_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:orange_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:magenta_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:light_blue_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:yellow_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:lime_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:pink_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:gray_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:light_gray_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cyan_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:purple_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:blue_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:brown_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:green_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:red_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:black_terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:white_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:orange_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:magenta_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:light_blue_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:yellow_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:lime_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:pink_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:gray_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:light_gray_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:cyan_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:purple_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:blue_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:brown_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:green_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:red_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:black_stained_glass_pane", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:acacia_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:cherry_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:dark_oak_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:mangrove_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:bamboo_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:bamboo_mosaic_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:slime_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:barrier", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:light", \
      block_states_group: 70 \
    }, \
    { \
      name: "minecraft:iron_trapdoor", \
      block_states_group: 13 \
    }, \
    { \
      name: "minecraft:prismarine", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:prismarine_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:dark_prismarine", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:prismarine_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:prismarine_brick_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:dark_prismarine_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:prismarine_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:prismarine_brick_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:dark_prismarine_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:sea_lantern", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:hay_block", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:white_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:orange_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:magenta_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:light_blue_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:yellow_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:lime_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:pink_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:gray_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:light_gray_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cyan_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:purple_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:blue_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:brown_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:green_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:red_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:black_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:terracotta", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:coal_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:packed_ice", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:sunflower", \
      block_states_group: 67 \
    }, \
    { \
      name: "minecraft:lilac", \
      block_states_group: 67 \
    }, \
    { \
      name: "minecraft:rose_bush", \
      block_states_group: 67 \
    }, \
    { \
      name: "minecraft:peony", \
      block_states_group: 67 \
    }, \
    { \
      name: "minecraft:tall_grass", \
      block_states_group: 67 \
    }, \
    { \
      name: "minecraft:large_fern", \
      block_states_group: 67 \
    }, \
    { \
      name: "minecraft:white_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:orange_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:magenta_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:light_blue_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:yellow_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:lime_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:pink_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:gray_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:light_gray_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:cyan_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:purple_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:blue_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:brown_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:green_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:red_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:black_banner", \
      block_states_group: 26 \
    }, \
    { \
      name: "minecraft:white_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:orange_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:magenta_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:light_blue_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:yellow_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:lime_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:pink_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:gray_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:light_gray_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:cyan_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:purple_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:blue_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:brown_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:green_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:red_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:black_wall_banner", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:red_sandstone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:chiseled_red_sandstone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cut_red_sandstone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:red_sandstone_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:oak_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:spruce_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:birch_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:jungle_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:acacia_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:cherry_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:dark_oak_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:mangrove_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:bamboo_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:bamboo_mosaic_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:stone_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:smooth_stone_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:sandstone_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:cut_sandstone_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:petrified_oak_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:cobblestone_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:brick_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:stone_brick_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:mud_brick_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:nether_brick_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:quartz_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:red_sandstone_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:cut_red_sandstone_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:purpur_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:smooth_stone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:smooth_sandstone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:smooth_quartz", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:smooth_red_sandstone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:spruce_fence_gate", \
      block_states_group: 3 \
    }, \
    { \
      name: "minecraft:birch_fence_gate", \
      block_states_group: 3 \
    }, \
    { \
      name: "minecraft:jungle_fence_gate", \
      block_states_group: 3 \
    }, \
    { \
      name: "minecraft:acacia_fence_gate", \
      block_states_group: 3 \
    }, \
    { \
      name: "minecraft:cherry_fence_gate", \
      block_states_group: 3 \
    }, \
    { \
      name: "minecraft:dark_oak_fence_gate", \
      block_states_group: 3 \
    }, \
    { \
      name: "minecraft:mangrove_fence_gate", \
      block_states_group: 3 \
    }, \
    { \
      name: "minecraft:bamboo_fence_gate", \
      block_states_group: 3 \
    }, \
    { \
      name: "minecraft:spruce_fence", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:birch_fence", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:jungle_fence", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:acacia_fence", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:cherry_fence", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:dark_oak_fence", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:mangrove_fence", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:bamboo_fence", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:spruce_door", \
      block_states_group: 1 \
    }, \
    { \
      name: "minecraft:birch_door", \
      block_states_group: 1 \
    }, \
    { \
      name: "minecraft:jungle_door", \
      block_states_group: 1 \
    }, \
    { \
      name: "minecraft:acacia_door", \
      block_states_group: 1 \
    }, \
    { \
      name: "minecraft:cherry_door", \
      block_states_group: 1 \
    }, \
    { \
      name: "minecraft:dark_oak_door", \
      block_states_group: 1 \
    }, \
    { \
      name: "minecraft:mangrove_door", \
      block_states_group: 1 \
    }, \
    { \
      name: "minecraft:bamboo_door", \
      block_states_group: 1 \
    }, \
    { \
      name: "minecraft:end_rod", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:chorus_plant", \
      block_states_group: 33 \
    }, \
    { \
      name: "minecraft:chorus_flower", \
      block_states_group: 46 \
    }, \
    { \
      name: "minecraft:purpur_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:purpur_pillar", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:purpur_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:end_stone_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:torchflower_crop", \
      block_states_group: 98 \
    }, \
    { \
      name: "minecraft:pitcher_crop", \
      block_states_group: 80 \
    }, \
    { \
      name: "minecraft:pitcher_plant", \
      block_states_group: 67 \
    }, \
    { \
      name: "minecraft:beetroots", \
      block_states_group: 23 \
    }, \
    { \
      name: "minecraft:dirt_path", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:end_gateway", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:repeating_command_block", \
      block_states_group: 43 \
    }, \
    { \
      name: "minecraft:chain_command_block", \
      block_states_group: 43 \
    }, \
    { \
      name: "minecraft:frosted_ice", \
      block_states_group: 23 \
    }, \
    { \
      name: "minecraft:magma_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:nether_wart_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:red_nether_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:bone_block", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:structure_void", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:observer", \
      block_states_group: 76 \
    }, \
    { \
      name: "minecraft:shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:white_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:orange_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:magenta_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:light_blue_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:yellow_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:lime_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:pink_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:gray_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:light_gray_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:cyan_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:purple_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:blue_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:brown_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:green_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:red_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:black_shulker_box", \
      block_states_group: 30 \
    }, \
    { \
      name: "minecraft:white_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:orange_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:magenta_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:light_blue_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:yellow_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:lime_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:pink_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:gray_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:light_gray_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:cyan_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:purple_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:blue_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:brown_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:green_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:red_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:black_glazed_terracotta", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:white_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:orange_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:magenta_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:light_blue_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:yellow_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:lime_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:pink_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:gray_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:light_gray_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cyan_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:purple_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:blue_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:brown_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:green_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:red_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:black_concrete", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:white_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:orange_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:magenta_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:light_blue_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:yellow_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:lime_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:pink_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:gray_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:light_gray_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cyan_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:purple_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:blue_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:brown_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:green_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:red_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:black_concrete_powder", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:kelp", \
      block_states_group: 65 \
    }, \
    { \
      name: "minecraft:kelp_plant", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:dried_kelp_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:turtle_egg", \
      block_states_group: 101 \
    }, \
    { \
      name: "minecraft:sniffer_egg", \
      block_states_group: 93 \
    }, \
    { \
      name: "minecraft:dead_tube_coral_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:dead_brain_coral_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:dead_bubble_coral_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:dead_fire_coral_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:dead_horn_coral_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:tube_coral_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:brain_coral_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:bubble_coral_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:fire_coral_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:horn_coral_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:dead_tube_coral", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:dead_brain_coral", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:dead_bubble_coral", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:dead_fire_coral", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:dead_horn_coral", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:tube_coral", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:brain_coral", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:bubble_coral", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:fire_coral", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:horn_coral", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:dead_tube_coral_fan", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:dead_brain_coral_fan", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:dead_bubble_coral_fan", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:dead_fire_coral_fan", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:dead_horn_coral_fan", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:tube_coral_fan", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:brain_coral_fan", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:bubble_coral_fan", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:fire_coral_fan", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:horn_coral_fan", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:dead_tube_coral_wall_fan", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:dead_brain_coral_wall_fan", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:dead_bubble_coral_wall_fan", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:dead_fire_coral_wall_fan", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:dead_horn_coral_wall_fan", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:tube_coral_wall_fan", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:brain_coral_wall_fan", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:bubble_coral_wall_fan", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:fire_coral_wall_fan", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:horn_coral_wall_fan", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:sea_pickle", \
      block_states_group: 91 \
    }, \
    { \
      name: "minecraft:blue_ice", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:conduit", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:bamboo_sapling", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:bamboo", \
      block_states_group: 19 \
    }, \
    { \
      name: "minecraft:potted_bamboo", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:void_air", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cave_air", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:bubble_column", \
      block_states_group: 34 \
    }, \
    { \
      name: "minecraft:polished_granite_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:smooth_red_sandstone_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:mossy_stone_brick_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:polished_diorite_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:mossy_cobblestone_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:end_stone_brick_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:stone_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:smooth_sandstone_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:smooth_quartz_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:granite_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:andesite_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:red_nether_brick_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:polished_andesite_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:diorite_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:polished_granite_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:smooth_red_sandstone_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:mossy_stone_brick_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:polished_diorite_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:mossy_cobblestone_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:end_stone_brick_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:smooth_sandstone_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:smooth_quartz_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:granite_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:andesite_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:red_nether_brick_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:polished_andesite_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:diorite_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:brick_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:prismarine_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:red_sandstone_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:mossy_stone_brick_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:granite_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:stone_brick_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:mud_brick_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:nether_brick_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:andesite_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:red_nether_brick_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:sandstone_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:end_stone_brick_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:diorite_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:scaffolding", \
      block_states_group: 87 \
    }, \
    { \
      name: "minecraft:loom", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:barrel", \
      block_states_group: 20 \
    }, \
    { \
      name: "minecraft:smoker", \
      block_states_group: 31 \
    }, \
    { \
      name: "minecraft:blast_furnace", \
      block_states_group: 31 \
    }, \
    { \
      name: "minecraft:cartography_table", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:fletching_table", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:grindstone", \
      block_states_group: 60 \
    }, \
    { \
      name: "minecraft:lectern", \
      block_states_group: 69 \
    }, \
    { \
      name: "minecraft:smithing_table", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:stonecutter", \
      block_states_group: 18 \
    }, \
    { \
      name: "minecraft:bell", \
      block_states_group: 24 \
    }, \
    { \
      name: "minecraft:lantern", \
      block_states_group: 66 \
    }, \
    { \
      name: "minecraft:soul_lantern", \
      block_states_group: 66 \
    }, \
    { \
      name: "minecraft:campfire", \
      block_states_group: 38 \
    }, \
    { \
      name: "minecraft:soul_campfire", \
      block_states_group: 38 \
    }, \
    { \
      name: "minecraft:sweet_berry_bush", \
      block_states_group: 23 \
    }, \
    { \
      name: "minecraft:warped_stem", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_warped_stem", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:warped_hyphae", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_warped_hyphae", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:warped_nylium", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:warped_fungus", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:warped_wart_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:warped_roots", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:nether_sprouts", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:crimson_stem", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_crimson_stem", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:crimson_hyphae", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:stripped_crimson_hyphae", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:crimson_nylium", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:crimson_fungus", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:shroomlight", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:weeping_vines", \
      block_states_group: 65 \
    }, \
    { \
      name: "minecraft:weeping_vines_plant", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:twisting_vines", \
      block_states_group: 65 \
    }, \
    { \
      name: "minecraft:twisting_vines_plant", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:crimson_roots", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:crimson_planks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:warped_planks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:crimson_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:warped_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:crimson_pressure_plate", \
      block_states_group: 8 \
    }, \
    { \
      name: "minecraft:warped_pressure_plate", \
      block_states_group: 8 \
    }, \
    { \
      name: "minecraft:crimson_fence", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:warped_fence", \
      block_states_group: 2 \
    }, \
    { \
      name: "minecraft:crimson_trapdoor", \
      block_states_group: 13 \
    }, \
    { \
      name: "minecraft:warped_trapdoor", \
      block_states_group: 13 \
    }, \
    { \
      name: "minecraft:crimson_fence_gate", \
      block_states_group: 3 \
    }, \
    { \
      name: "minecraft:warped_fence_gate", \
      block_states_group: 3 \
    }, \
    { \
      name: "minecraft:crimson_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:warped_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:crimson_button", \
      block_states_group: 0 \
    }, \
    { \
      name: "minecraft:warped_button", \
      block_states_group: 0 \
    }, \
    { \
      name: "minecraft:crimson_door", \
      block_states_group: 1 \
    }, \
    { \
      name: "minecraft:warped_door", \
      block_states_group: 1 \
    }, \
    { \
      name: "minecraft:crimson_sign", \
      block_states_group: 10 \
    }, \
    { \
      name: "minecraft:warped_sign", \
      block_states_group: 10 \
    }, \
    { \
      name: "minecraft:crimson_wall_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:warped_wall_sign", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:structure_block", \
      block_states_group: 95 \
    }, \
    { \
      name: "minecraft:jigsaw", \
      block_states_group: 63 \
    }, \
    { \
      name: "minecraft:composter", \
      block_states_group: 49 \
    }, \
    { \
      name: "minecraft:target", \
      block_states_group: 61 \
    }, \
    { \
      name: "minecraft:bee_nest", \
      block_states_group: 22 \
    }, \
    { \
      name: "minecraft:beehive", \
      block_states_group: 22 \
    }, \
    { \
      name: "minecraft:honey_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:honeycomb_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:netherite_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:ancient_debris", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:crying_obsidian", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:respawn_anchor", \
      block_states_group: 86 \
    }, \
    { \
      name: "minecraft:potted_crimson_fungus", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_warped_fungus", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_crimson_roots", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_warped_roots", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:lodestone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:blackstone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:blackstone_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:blackstone_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:blackstone_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:polished_blackstone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:polished_blackstone_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cracked_polished_blackstone_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:chiseled_polished_blackstone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:polished_blackstone_brick_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:polished_blackstone_brick_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:polished_blackstone_brick_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:gilded_blackstone", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:polished_blackstone_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:polished_blackstone_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:polished_blackstone_pressure_plate", \
      block_states_group: 8 \
    }, \
    { \
      name: "minecraft:polished_blackstone_button", \
      block_states_group: 0 \
    }, \
    { \
      name: "minecraft:polished_blackstone_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:chiseled_nether_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cracked_nether_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:quartz_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:white_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:orange_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:magenta_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:light_blue_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:yellow_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:lime_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:pink_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:gray_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:light_gray_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:cyan_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:purple_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:blue_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:brown_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:green_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:red_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:black_candle", \
      block_states_group: 28 \
    }, \
    { \
      name: "minecraft:candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:white_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:orange_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:magenta_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:light_blue_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:yellow_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:lime_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:pink_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:gray_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:light_gray_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:cyan_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:purple_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:blue_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:brown_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:green_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:red_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:black_candle_cake", \
      block_states_group: 29 \
    }, \
    { \
      name: "minecraft:amethyst_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:budding_amethyst", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:amethyst_cluster", \
      block_states_group: 16 \
    }, \
    { \
      name: "minecraft:large_amethyst_bud", \
      block_states_group: 16 \
    }, \
    { \
      name: "minecraft:medium_amethyst_bud", \
      block_states_group: 16 \
    }, \
    { \
      name: "minecraft:small_amethyst_bud", \
      block_states_group: 16 \
    }, \
    { \
      name: "minecraft:tuff", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:calcite", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:tinted_glass", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:powder_snow", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:sculk_sensor", \
      block_states_group: 89 \
    }, \
    { \
      name: "minecraft:calibrated_sculk_sensor", \
      block_states_group: 37 \
    }, \
    { \
      name: "minecraft:sculk", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:sculk_vein", \
      block_states_group: 58 \
    }, \
    { \
      name: "minecraft:sculk_catalyst", \
      block_states_group: 88 \
    }, \
    { \
      name: "minecraft:sculk_shrieker", \
      block_states_group: 90 \
    }, \
    { \
      name: "minecraft:oxidized_copper", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:weathered_copper", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:exposed_copper", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:copper_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:copper_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:deepslate_copper_ore", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:oxidized_cut_copper", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:weathered_cut_copper", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:exposed_cut_copper", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cut_copper", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:oxidized_cut_copper_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:weathered_cut_copper_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:exposed_cut_copper_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:cut_copper_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:oxidized_cut_copper_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:weathered_cut_copper_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:exposed_cut_copper_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:cut_copper_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:waxed_copper_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:waxed_weathered_copper", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:waxed_exposed_copper", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:waxed_oxidized_copper", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:waxed_oxidized_cut_copper", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:waxed_weathered_cut_copper", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:waxed_exposed_cut_copper", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:waxed_cut_copper", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:waxed_oxidized_cut_copper_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:waxed_weathered_cut_copper_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:waxed_exposed_cut_copper_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:waxed_cut_copper_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:waxed_oxidized_cut_copper_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:waxed_weathered_cut_copper_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:waxed_exposed_cut_copper_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:waxed_cut_copper_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:lightning_rod", \
      block_states_group: 71 \
    }, \
    { \
      name: "minecraft:pointed_dripstone", \
      block_states_group: 81 \
    }, \
    { \
      name: "minecraft:dripstone_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cave_vines", \
      block_states_group: 40 \
    }, \
    { \
      name: "minecraft:cave_vines_plant", \
      block_states_group: 41 \
    }, \
    { \
      name: "minecraft:spore_blossom", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:azalea", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:flowering_azalea", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:moss_carpet", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:pink_petals", \
      block_states_group: 77 \
    }, \
    { \
      name: "minecraft:moss_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:big_dripleaf", \
      block_states_group: 25 \
    }, \
    { \
      name: "minecraft:big_dripleaf_stem", \
      block_states_group: 14 \
    }, \
    { \
      name: "minecraft:small_dripleaf", \
      block_states_group: 92 \
    }, \
    { \
      name: "minecraft:hanging_roots", \
      block_states_group: 21 \
    }, \
    { \
      name: "minecraft:rooted_dirt", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:mud", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:deepslate", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:cobbled_deepslate", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cobbled_deepslate_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:cobbled_deepslate_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:cobbled_deepslate_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:polished_deepslate", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:polished_deepslate_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:polished_deepslate_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:polished_deepslate_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:deepslate_tiles", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:deepslate_tile_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:deepslate_tile_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:deepslate_tile_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:deepslate_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:deepslate_brick_stairs", \
      block_states_group: 12 \
    }, \
    { \
      name: "minecraft:deepslate_brick_slab", \
      block_states_group: 11 \
    }, \
    { \
      name: "minecraft:deepslate_brick_wall", \
      block_states_group: 17 \
    }, \
    { \
      name: "minecraft:chiseled_deepslate", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cracked_deepslate_bricks", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:cracked_deepslate_tiles", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:infested_deepslate", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:smooth_basalt", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:raw_iron_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:raw_copper_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:raw_gold_block", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_azalea_bush", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:potted_flowering_azalea_bush", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:ochre_froglight", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:verdant_froglight", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:pearlescent_froglight", \
      block_states_group: 6 \
    }, \
    { \
      name: "minecraft:frogspawn", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:reinforced_deepslate", \
      block_states_group: 7 \
    }, \
    { \
      name: "minecraft:decorated_pot", \
      block_states_group: 53 \
    } \
  ]
